LeelaChessZero/lc0

- meson.build
- meson_options.txt
This patch can be used to disable specific lc0 backends using the meson command line. The original intention was to disable the TensorFlow backend, which can be done by specifying -Dtf=false, but the final version allows -Dopencl=false -Dcudnn=false and -Dblas=false as well.
> meson options to disable lc0 backends

- README.md
Build instructions for mac added. Uses OpenCL backend.
Best if someone with a virgin Mac system tests this to see if I have got all the prerequisits in.
> Update README.md with build instructions for Mac

- src/neural/loader.cc
- src/utils/filesystem.posix.cc
This development makes GetFileList to include soft link *when they actually resolve to a regular file*.
The same simple development with just including  DT_LNK  is the allowed types could prevent lc0 to list the directory if a broken link was present in the directory.
Alternatively, we could add a "bool FileExists(cont char*)" in the filesystem interface and call the function.
> Filesystem_posix: GetFileList to include non-broken soft links.

- src/engine.cc
http://wbec-ridderkerk.nl/html/UCIProtocol.html
Note that it is ambiguous in the specification if options may be set/reset after isready, but it is clear that isready should finish all expensive initialization, options or not (quoting the link):
// the engine has sent all parameters and is ready
uciok
// Note: here the GUI can already send a "quit" command if it just wants to find out
//       details about the engine, so the engine should not initialize its internal
//       parameters before here.
// now the GUI sets some values in the engine
// set hash to 32 MB
setoption name Hash value 32
// init tbs
setoption name NalimovCache value 1
setoption name NalimovPath value d:\tb;c\tb
// waiting for the engine to finish initializing
// this command and the answer is required here!
isready …
> Per UCI protocol example, `isready` directly initializes network (fixes startup lag)

- src/chess/uciloop.cc
The UCI loop is try-catched but atoi (an old std-c routine **crashes**).
> ./lc0 --backend="blas"
_
|   _ | |
|_ |_ |_| built Jun  2 2018
go nodes
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: stoi: no conversion
Abort trap: 6
Now:
go nodes xyz
error invalid value xyz
go nodes
error expected value after nodes
> Fix crash where uci command "go nodes" is entered.

- src/engine.cc
- src/mcts/node.cc
- src/mcts/node.h
Memory leak from #34 was only half a bug.
* It was expected to call garbage collection after returning a best move, but didn't. (bug)
* It was expected to cal GC during "isready". That worked.
> Do GC in a separate thread.

- src/engine.cc
I know that's controversial (especially as it diverges from a0 paper, namely in policy softmax=2.2), but it shown good results.
Feel free to reject. :)
> Switch to params, suggested by @ASilver.

- src/mcts/node.cc
- src/mcts/node.h
- src/selfplay/game.cc
- src/selfplay/game.h
- src/selfplay/tournament.cc
- src/selfplay/tournament.h
To close #26.
This option should work regardless of kShareTrees - but in case share trees is also disabled I made cache sharing automatic if networks are equal even if share trees is not true. It looks like a safe performance improvement for that scenario... I think.
> Add no tree reuse option for tournaments.

- meson.build
The BLAS include directories were added in the build unconditionally if the MKL or OpenBLAS library was detected. However the libraries may be present without the include directories, and the build would fail even when building only the cuDNN backend.
> build if BLAS includes are missing but not required

- src/neural/network_random.cc
> Mix in the plane value when calculating random backend hash.

- meson.build
- meson_options.txt
Improvements discussed in #58: 
1. Each BLAS library can be enabled/disabled individually;
2. A warning is generated if building the OpenCL backend but no BLAS library is detected.
Also fixes the location of transform.cc (that was moved) when building the OpenCL backend but not the BLAS backend.
> BLAS backend build system usability improvements

- src/mcts/node.cc
- src/mcts/node.h
- src/mcts/search.cc
- src/mcts/search.h
This is a selective reversion of cda3a4e4281b84ce38a472e99f03e9f57bad7d9f.
Fixes #91.
Credit to Tilps for spotting it. I was reviewing, and would have found it eventually, but it probably would have taken me several hours in my... less than fully awake state right now.
> Fix the improper handling of terminal V values. 

- src/mcts/search.cc
This PR fixed a data race condition that was discovered when investigating #98. The fix is by @mooskagh, who analyzed the thread sanitizer output. It currently appears the race condition is unrelated to the crashes that issue pertains to.
> fix data race condition

- src/engine.cc
Weighs the time to give each move by a parameterised peaking function.
This has the effect of changing the time curve to adjustably spend less time on earlier moves and more time in the midgame.
The weightings are parameterised by:
- Peak: The ply to peak the weightings given to each move
- Width: How wide the time curve is (I think this is approximately how far after the peak the inflection point will be)
Note: The parameters change the shape of the weights given to each move, not the time curve directly.
Because `Scale thinking time`effectively changes the time curve, I've just removed it since you should be able to get similar effects by changing parameters of the weighting function.
- Example of weights given with _peak=30_ and _width=30_
- Example of weights given with _peak=45_ and …
> Add adjustable peaking time curve

- src/chess/callbacks.h
- src/chess/uciloop.cc
- src/chess/uciloop.h
- src/selfplay/game.cc
- src/selfplay/game.h
- src/selfplay/loop.cc
- src/selfplay/tournament.cc
This is untested right now as I'm still making the changes to the client.
> Track false positive resign thresholds for non-resign tournament games.

- meson.build
Specifying -march=native implies -mtune=native (see https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html). I removed the latter from the build config.
> Remove redundant compiler flag

- README.md
- added missing Ubuntu 16.04 clang-6.0 installation step
- added OpenBLAS to list of possible backends (Linux generic)
> Updated README.md Linux build instructions:

- .circleci/Dockerfile
- .circleci/config.yml
Initial CircleCI support. Builds using Ubuntu Linux 18.04.
Build log here: https://circleci.com/gh/DanielUranga/lc0/10
This is an attempt to start solving https://github.com/LeelaChessZero/lc0/issues/50
> CircleCI Linux automatic builds

- src/engine.cc
2267 games update. 
left peak 65. right peak 80. peak ply 27. scale 1.95 was tested around 1900 games, first result of actually beating the initial time management according to ZZ.
```   # PLAYER                                      :  RATING  ERROR   GAMES
1 LC0_Id9149_SM1.95_TCP27_TCLW65_TCRW80       :      11     43     100
2 LC0_Id9149_SM1.8_TCP41_TCLW1000_TCRW39.5    :       0   ----     100
```
11 elo ahead instead of 28 behind for a gain of about 40 elo since last commit. at 48s+0.2
> Clop time managment update

- src/chess/bitboard.h
A value of 63 would correspond to the square h8, rather than h7 as is.
> Fix minor documentation error

- src/mcts/node.cc
- src/mcts/node.h
- src/mcts/search.cc
- src/mcts/search.h
- src/utils/cache.h
Half for reference relative to the bug fix, half serious to get that max mem savings. As far as debug usefulness goes, is there a debug macro defined by meson that we can use to conditionally include V outputs? (By which I mean we could have a conditionally-compiled std::vector<evals> in the `Search` for printing purposes)
> Remove v_ from Node, take 2

- src/engine.cc
Updated to 1.95 and 26.2 from over 5000 games of clop at 30+.17. retuned left and right for close to 1000 games at 60+1. And got these values. ZZ tested this compared to equal with less increment as well.
```
TC 192s+0.8s/move match running, 28/100 games played
1 LC0_Id9149_SM1.95_TCP26.2_TCLW82_TCRW74     :       0     35      28
2 LC0_Id9149_SM1.8_TCP41_TCLW1000_TCRW39.5    :       0   ----      28`
```
This shows even though I tuned for a 60/1 ratio (wheras tcec is 180 ratio) it works just as good as original even with a 240 ratio. (Although likely would be stronger saving a tiny bit more time for end compared to tune)
> Update engine.cc time management to slower CLOP tune

- src/mcts/search.cc
Please see attached text document for full description of this mutex optimization for multi-GPU scaling
[mutex_optimization_comment.txt](https://github.com/LeelaChessZero/lc0/files/2173304/mutex_optimization_comment.txt)
> Multiplexing mutex optimization for improvement of multi-GPU scalability

- meson.build
Search for OpenBLAS headers in array `get_option('openblas_include')`. Add the first directory that contains `cblas.h` to `includes`.
This fixes following build meson build error on Ubuntu 18.04 with `libopenblas-dev` installed
> meson.build:155:6: ERROR:  Include dir /usr/include/openblas/ does not exist.
> Meson: added search for OpenBLAS include directories

- appveyor.yml
This enables building cuDNN lc0 executables for windows, in addition to openblas and OpenCL ones. Also the openblas and OpenCL executables are packaged with the appropriate dlls in respective zip files.
> cuDNN windows build for AppVeyor

- meson.build
- meson_options.txt
- subprojects/gtest.wrap
Adds a fallback gtest submodule to be built in case gtest is not installed, and an option to disable the building of tests.
> add gtest option and fallback in meson

- appveyor.yml
If I created the correct encrypted authentication token this will upload the following generated zip files to the github release page on each release: lc0-blas.zip, lc0-openl.zip and lc0-cudnn.zip
If it doesn't work we'll need to figure out how to generate the correct token.
> try to deploy appveyor packaged zips to github

- src/utils/optionsdict.cc
* strings are also allowed where identifiers are allowed:
"blah"(1,2,3) instead of blah(1,2,3)
* identifiers can contain punctuation -_./ (so cudnn-fp16 is supported as subdictionary name)
> Changes in backend-opts parsing.

- appveyor.yml
- meson.build
This runs the tests on appveyor together with the blas build. It was necessary to increase the test timeout in meson.build from the default 3 seconds to 90 seconds (which is around double what is strictly needed).
> run tests on appveyor

- appveyor.yml
Appveyor updated their VS2017 image to the latest one, that cuda complains about, so disable the cuda build until a solution is found (I'm looking for one).
> Disable cuda builds for the time being

- src/mcts/node.h
- src/mcts/search.cc
Moved the comparison from Edge_Iterator to its parent EdgeAndNode, which should operate identically.
Also, the implicit bool conversion was apparently being used in the sorting in PrefetchIntoCache, so that had to be fixed as well.
search.cc:614 was the comparison in question; it always came up false (except when best_move_edge_ was null), thus preventing smart pruning, thus totally screwing up Leela's time usage. (First noticed on TCEC bonus matches)
Fixed output:
```
child b1a3 best move e2e4 differ? 1
child b1c3 best move e2e4 differ? 1
child g1f3 best move e2e4 differ? 1
child g1h3 best move e2e4 differ? 1
child a2a3 best move e2e4 differ? 1
child a2a4 best move e2e4 differ? 1
child b2b3 best move e2e4 differ? 1
child b2b4 best move e2e4 differ? 1
child c2c3 best move e2e4 differ? 1 …
```
> Fix smart pruning, which was broken by improper implicit comparison

- appveyor.yml
Use vs2015 compiler on appveyor to fix cuda breaking with the updated vs2017 version. Also update cuda to the latest version (9.2.148)
> Fix appveyor cuda build (and update cuda)

- src/chess/bitboard.cc
- src/chess/bitboard.h
Turns out that the reason for the extraneous queen promotions was because Mirror was using 0x instead of 0b for the bitmask, so it was setting the wrong bits
> Reduce Move size from 4 bytes to 2 (take two)

- src/chess/bitboard.h
Broken by the reduce Move size PR, which incorrectly changed how castles are compared. Previously, they weren't compared, `Move::operator==` only compared `from`, `to`, and promotion. We revert now to that behavior, since that's the information specified by UCI `position moves ...` long algebraic notation.
> Fix castling comparison to not crash NodeTree

- src/mcts/search.cc
- src/mcts/search.h
These two were visible in the UCI PV in certain situtations, where the putative PV differed from what was later reported as the best move.
This commit fixes #167, which is the corresponding bug report.
Both bugs arose from circumstances where best_move_edge_ differed from what GetBestChildNoTemperature(root_node_) would report.
One such circumstance was that, after tree reuse, when starting a second Search, best_move_edge_ was null, which means if the subsequent search failed to playout the previous/actual best node (from the reused tree), then by the updates in DoBackupNode, best_move_edge_ would be incorrectly set to recently searched nodes, which didn't include the previous most searched node, and thus disagree with GBCNT.
(Such a circumstance can arise either by contrived FPUR hacks, …
> Fix two minor bugs in best_move_edge_ tracking

- appveyor.yml
This will make Appveyor build all commits, even trivial ones that only change text files. There is a misalignment with GitHub that expects a status report, while Appveyor doesn't process the commits at all and thus no status is reported. The other two commits in this series save some time by building in parallel and caching the files than meson downloads.
> Appveyor: do not skip commits to fix clash with GitHub status expectations

- meson.build
It turns out that there are many systems with only protobuf or protoc installed. Since both have to be available and the same version, this patch couples their detection and uses the fallback submodule if either is missing.
> Use submodule if either protobuf or protoc not found

- src/engine.cc
- src/neural/loader.cc
- src/neural/loader.h
- src/selfplay/tournament.cc
The DiscoveryWeightsFile() function for protobuf compressed files didn't work. This PR makes sure it works again by checking the file header of a gzipped file. Unfortunately gzopen() doesn't distinguish between opening a regular file or a gzipped file.
Furthermore, binary protobuf does not contain some kind of header but goes straight into serialized data. I don't know of a better way to check for these type of files.
> discover gzipped files

- README.md
Updated instructions for Ubuntu and Macos, submodule update required for protobuf
> Add submodule update to build instructions

- appveyor.yml
- meson.build
- meson_options.txt
The objective of this patch is to allow a precompiled protobuf to be used on windows/appveyor. This requires the protobuf library and include paths to be configurable for the build, which is achieved by replacing the dependency() with a cc.find_library() and include_directories() pair, together with the relevant meson options.
The appveyor.yml change builds and installs protobuf on a path that is cached for subsequent builds. Also the caching of meson is removed since it turns out to be slower than a fresh install.
This has been tested on ubuntu 16.04, windows and appveyor. Additional testing, in particular on osx is welcome.
> make protobuf paths configurable and build/cache on appveyor

- appveyor.yml
- dist/README-cuda.txt
This patch adds the required dlls and txt files to the zip created by appveyor for every release, to be uploaded on github. An example here: https://ci.appveyor.com/api/buildjobs/1ytuv252w9l8my5t/artifacts/lc0-windows-cuda.zip
> package cuda/cudnn, closes #214

- src/chess/board.cc
The popcnt instruction is not supported on older core processors. The fact that even on those this is only rarely encountered shows this is not a speed critical piece of code. However since it was used just to check for less than 4 pieces on the board, the replacement code can be very efficient. Microbenchmarks show the new code to be slightly faster than a single popcnt call, but it replaces two of them so it should be a win regardless.
> Remove use of popcnt, fixes #174.

- src/mcts/node.cc
This case can currently happen due to force moves only getting a single visit.
(It is possible that this should not be the case with resign on, but that may require more discussion.)
> Allow generation of training data for single visit

- appveyor.yml
The ispc version of the Winograd transform gives about 5% more nps than the c++ version.
This makes executables optimized for multiple targets, using the ispc option to select the appropriate one at run time.
> Make appveyor use ispc for blas builds

- src/engine.cc
Currently the weights file is only printed when found through auto discovery.  With config files, it would also be nice to see it always printed as a sanity check.
> Print where weights are loaded from when no auto discover.

- appveyor.yml
Setting the WholeProgramOptimization property when making a release. This was found to give a few % speedup even on gpus.
> Appyeyor will use lto for releases

- src/mcts/node.cc
- src/mcts/node.h
- src/mcts/search.cc
- src/mcts/search.h
This computes depth more efficiently and replaces full_depth with the more informative average depth:
1. both max_depth and full_depth are removed from the node structure freeing space
2. the checking of all siblings for full_depth computation is no longer needed
3. full_depth rarely got larger than 5 even on fast machines and long searches
4. average depth replaces full_depth as a more informative measure
5. max_depth reflects search depth not tree depth
6. max_depth is consistent with length of pv displayed (if pv stems from the max depth line)
7. max_depth and cum_depth (for averaging) are computed in a two step process, first per batch and only after the mutexed search->max_depth and search->cum_depth are updated. This is in preparation of a mutex reorg.
8. For discussion: average …
> Efficient and informative depth computation.

- meson.build
Adding `--pic` flag (position independent code) solves linking error with object code generated from ispc. This also allows building binary with multiple architectures, that was for this error disabled with meson flag  `ispc_native_only`
Error that should be fixed:
`../winograd_ispc.o: relocation R_X86_64_32S against .rodata.cst32 can not be used when making a PIE object; recompile with -fPIC`
> ispc  fix linking error

- README.md
Fix the appveyor link to point to the new org account.
> Fix appveyor link in readme

- README.md
Remove the redundant 'the' from the Nvidia license.
> Fix minor readme typo

- src/mcts/node.cc
- src/mcts/node.h
This saves 2 actual bytes, or 4 aligned bytes after the Move savings, resulting in roughly 40% savings in total tree size:
35\*8 + 64 = 344  bytes per node --> 35\*4 + 64 = 204 bytes per node
```
|   _ | |
|_ |_ |_| built Jul 14 2018
Move size 2 for estimated Edge size 4 vs actual Edge size 4 Node size 64 for total estimated bytes/Node of 204
go nodes 5
Creating backend [blas]...
BLAS vendor: OpenBlas.
OpenBlas [NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge].
OpenBlas found 8 Sandybridge core(s).
OpenBLAS using 1 core(s) for this backend.
BLAS max batch size is 256.
info depth 2 seldepth 2 time 33 nodes 2 score cp 6 hashfull 0 nps 60 pv d2d4 d7d5
info depth 2 seldepth 3 time 60 nodes 4 score cp 5 hashfull 0 nps 66 pv d2d4 d7d5 c2c4
info depth 2 seldepth 3 time 74 nodes 5 score cp 5 …
```
> Change Edge::p_ from float to uint16_t

- src/mcts/search.cc
As @mooskagh asked. Only the option is renamed, the variable names are left as they were.
> renamed smart-pruning-aggresiveness option to smart-pruning

- src/utils/configfile.cc
Configuration files were recently implemented in master via this pull request:  https://github.com/LeelaChessZero/lc0/pull/231
A couple of people suggested allowing the ability to omit the starting '--' to the argument name.  With this change, the following two lines are equivalent:
--threads=1
threads=1
> Allow configuration file arguments to omit leading '--'

- src/mcts/search.cc
Edge::SetP does some rounding, meanwhile the "total unscaled policy for all moves" to be used as the scale factor was computed before this rounding.
In the rare case of there being only one legal move where the rounding didn't have anything to cancel out with on average, this could mean if the only-legal-move policy was sufficiently large and also rounded up when stored, then the "total" variable was slightly smaller than the actual edge->GetP() value, which meant that the scale = 1/total value times the GetP() value could rarely exceed 1 by a few parts per thousand. This wouldn't affect search behavior of course (especially when there's only one legal move), but it triggered the assert.
The fix is to increment the total with the rounded value, not the unrounded value.
> Fix minor bug in NN -> Edge policy storage

- src/mcts/search.cc
- src/mcts/search.h
- src/neural/blas/winograd_convolution3.cc
- src/neural/cache.cc
- src/neural/cache.h
Currently if the first node in a batch turns out to be a cache hit, it's back-propagated immediately without gathering full batch and without querying NN.
This PR extends that (behind `--out-of-order-eval` flag) to:
- Cache hit at any index in the batch
- Also to terminal nodes
When during the batch collection such node is encountered, it's processed out of order. On the next iteration, batch gathering continues from where previous attempt stopped.
Gives +8% nps.
(Having `--cache-history-length=0` with that change gives +12% nps on top of that, may be worth to reconsider using it, maybe it will translate to Elo gain this time)
> Out of order eval for terminal nodes and cache hits.

- src/utils/configfile.cc
- src/utils/configfile.h
This fixes issue https://github.com/LeelaChessZero/lc0/issues/295.
If you run lc0 with the following command, it reports that the config file was found when in fact it was not.
`./lc0 --config=`
You would run the above command if you wanted to override using the default lc0.config file.  This PR will not print that the config file at ./ was found which is confusing since no config file was actually loaded.
I also changed the ParseFile function signature to use `const std::string& `instead of `const std::string`.
> Fix reporting that config file was loaded when it wasn't

- src/mcts/search.cc
- src/mcts/search.h
This is untested, but should probably work to some extent I think.
Its not a 'complete' root probe support as it has two cases where it can fail.
1) If after search GetChildrenVisits is 0 the move selected may not be optimal.
2) If tree reuse brings over a lot of visits, those visits will not have been restricted to the root probe list, so the new visits to the filtered list might not have time to catch up, and an invalid move will be made.
Both of these could be fixed by adding a root probe call to GetBestChild* and applying filtering in there just like it currently does for searchmoves.
> Add minimal root probing support.

- build.sh
There were some complaints about build.sh removing the build directory, so here is a modifications that if it exists runs `meson configure` and reuses the existing directory. As far as I can tell/test, this does the correct thing, with ninja rebuilding everything needed.
The second part allows adding command line options after the (optional) build type, that are passed directly to meson.
> Changes to build.sh

- src/neural/network_mux.cc
notify_one in MutexComputing::NotifyReady in some cases ends up running after/while its object is being destroyed after SearchWorker::ExecuteOneIteration inside SearchWorker::InitializeIteration  by a different thread corrupting memory.
*Force dataready_cv_.notify_one(); to finish before the lock is released to a different thread
*Fixes Crash in multiplexed setup with blas, opencl and heavy threading #98
> Fix data race in MuxingComputation::NotifyReady with heavy threading

- src/mcts/search.cc
the bug was caused by all cumulative sum elements being 0 if temperature was low enough
fixed by scaling the elements so that their maximum will always be 1.0
> fix move selection bug at low temperatures

- src/mcts/search.cc
- src/mcts/search.h
I am thinking that this with -0.7 , or maybe -0.4 and a slight temperature reduction (0.95) could be a good test to run on parallel training after tb rescoring - so it would be good if we could get this in for 0.18.
Note that the assert(max_n > 0.0) can fire if the delta is less than or equal to -1 and the visits are not sufficient.  I would hope there is no actual use case where someone would be trying to test such strange combinations...
Note that delta == -1 is almost, but not quite equivalent the separate proposal to discard single visits.
> Add ability to offset visits going in to temperature calculation.

- src/chess/uciloop.cc
A PR for an Easter egg is part of the joke. This adds the [xyzzy](https://en.wikipedia.org/wiki/Colossal_Cave_Adventure#Xyzzy) command to the UCI parser. The reply is "Nothing happens."
> Add 'Colossal Cave' Easter egg

- src/mcts/search.cc
r?@Tilps Fix some corner cases introduced by #359 and simplifying code while maintaining #337.
1) Positive offset allows move selection even when children have no visits, so don't condition temperature selection on children visits.
Before `--temp-visit-offset=2` (highest prior is picked):
```
info string b2b3  (230 ) N:       0 (+ 0) (P:  1.32%) (Q:  0.03456) (U: 0.01580) (Q+U:  0.05036) (V:  -.----) 
info string g1f3  (159 ) N:       0 (+ 0) (P: 26.54%) (Q:  0.03456) (U: 0.31846) (Q+U:  0.35301) (V:  -.----) 
bestmove g1f3
```
After `--temp-visit-offset=2` (any move can be picked with no visits):
```
info string b2b3  (230 ) N:       0 (+ 0) (P:  1.32%) (Q:  0.03456) (U: 0.01580) (Q+U:  0.05036) (V:  -.----) 
info string g1f3  (159 ) N:       0 (+ 0) (P: 26.54%) (Q:  0.03456) (U: …
```
> Fix temperature selection with positive and negative offsets

- src/mcts/node.h
Addresses #369, compile fails on 32-bit platforms.
> 32bit compile support (Raspberry Pi)

- src/mcts/search.cc
1. Bug with kSmartPruningToleranceNodes meaning millinodes is fixed
2. kSmartPruningToleranceNodes set to 500
3. kSmartPruningToleranceMs set to 400 (was 200).
On very slow configurations (e.g. CPU) this will cause smart pruning to almost never trigger, but for now it's better than instamoving.
> Quick fix for smart pruning tolerance to avoid instamoves.

- src/chess/bitboard.h
- src/utils/bititer.h
Add win32-compatible versions of those functions so it doesn't fail to compile when using 32 bits Visual Studio.
> Add Win32-compatible version of "popcount" and "bitscan"

- appveyor.yml
This makes the packaged zip include the tag in the filename. Example [lc0-v0.17.99-windows-cuda.zip](https://ci.appveyor.com/api/buildjobs/94im0tv8fbsp2ad7/artifacts/lc0-v0.17.99-windows-cuda.zip). Adding the tag to the executable as well is possible, but then it would have to be renamed back to lc0.exe for use with the training client.
> add tag to zip filename

- src/chess/position.cc
- src/chess/position.h
- src/chess/position_test.cc
- src/mcts/search.cc
- src/syzygy/syzygy.cc
- src/syzygy/syzygy.h
- src/syzygy/syzygy_test.cc
This was an oversight on my part when converting from cfish movegen to our movgen.
> Correct implementation of root_probe to consider all prior potential repeats, not just current move.

- meson.build
Instead of looking for nvcc in the cuda 9.1 and 9.2 specific paths, look in /usr/local/cuda/bin which is linked to the correct directory. This works fine as a default with the library and include path. Alternatively, nvcc should be on the path, which works on windows.
I would like some feedback from different linux and macos versions before merging this.
> use invariant path for nvcc

- src/neural/opencl/OpenCL.h
There is an incompatibility between the OpenCL headers and 32 bit MSVC, when the OpenCL target version is 1.2 (our default). This patch sets the target version to 1.1 when building with 32 bit MSVC to avoid this
> set CL_HPP_TARGET_OPENCL_VERSION to 110 for 32 bit windows

- src/utils/optionsparser.cc
The official UCI specification has min and max in lower case. pr425 changed these to upper case which broke a few GUIs. This pr reverts them to lower case.
> Corrected case of min/max to UCI specification

- src/mcts/node.cc
Fix a minor data race on exiting application.
```
==================
WARNING: ThreadSanitizer: data race (pid=31556)
Write of size 1 at 0x0000013ac798 by main thread:
#0 ~NodeGarbageCollector /home/chris/src/leela/build/release/../../src/mcts/node.cc:67 (lc0+0x56ff26)
#1 cxa_at_exit_wrapper(void*) tsan_interceptors.cc.o:? (lc0+0x439583)
Previous read of size 1 at 0x0000013ac798 by thread T1:
#0 lczero::(anonymous namespace)::NodeGarbageCollector::Worker() /home/chris/src/leela/build/release/../../src/mcts/node.cc:88 (lc0+0x5743a7)
#1 operator() /home/chris/src/leela/build/release/../../src/mcts/node.cc:55 (lc0+0x574308)
#2 void std::_Bind_simple<lczero::(anonymous namespace)::NodeGarbageCollector::NodeGarbageCollector()::{lambda()#1} ()>::_M_invoke<>(std::_Index_tuple<>) …
```
> Fix minor data race condition on application exit

- src/engine.cc
- src/mcts/node.cc
- src/mcts/node.h
- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/mcts/search.h
If there is a collision, estimate how much more visits will be collisions and apply them at once.
The same for terminal node visits.
> Batch collisions and terminal node visits.

- src/neural/opencl/OpenCL.cc
- src/neural/opencl/OpenCLTuner.cc
OpenCL backend tuned the sgemm for wrong matrix size. With the correct dimension nps increases from 630 to 930 using batch size of 16.
> Fix OpenCL tuner matrix size

- src/engine.cc
- src/selfplay/tournament.cc
- src/utils/optionsdict.cc
- src/utils/optionsdict.h
When backend options are used like: 
lc0.exe selfplay --backend-opts="cudnn(threads=1, minibatch-size=512)"
the variable dict used before will get invalid, when the methode FromString will end, which lead to an exception in the debug mode and might lead to bigger issues later in the runtime mode, when the options are overwritten by random.
I'm sorry if something is wrong with my pull request. It's my first try.
> Exception during lc0 startup - using backend opts

- src/engine.cc
- src/mcts/search.cc
- src/mcts/search.h
The value passed to a 'go depth' UCI command
is parsed but not used. The result is that
'go depth 1' is equal to a 'go infinite'.
For a GUI that doesn't support 'go nodes', like
pychess, this means that if you set the 'difficulty
slider' to any value - the engine doesn't move
until it is stop-ped. To have a better experience
it seems logical to more or less stop once the
printed uci info 'depth' value reaches the requested
depth.
Example engine output after patch:
ucinewgame
position startpos moves e2e4
go depth 3
info depth 1 seldepth 2 time 194 nodes 3 score cp -5 hashfull 0 nps 15 tbhits 0 pv c7c5 d2d4
info depth 2 seldepth 3 time 310 nodes 9 score cp -10 hashfull 0 nps 29 tbhits 0 pv c7c5 c2c3 g8f6
info depth 3 seldepth 4 time 401 nodes 20 score cp -7 hashfull 0 nps 49 tbhits 0 pv …
> Do something useful with a "go depth N" value.

- src/utils/configfile.cc
- src/utils/configfile.h
The -n short option works as a toggle. This means that ProcessAllFlags() should not be called twice, since then the value is reset to the default. Unfortunately, this is exactly what is happening since we call it once to get the config file to open, and then once more to actually do the final option parsing. This patch introduces a ProcessConfigFlag function to just look for this specific option and get the filename.
> Do not parse flags twice (just to find config file)

- src/engine.cc
- src/mcts/search.cc
- src/mcts/search.h
- src/selfplay/game.cc
- src/selfplay/game.h
- src/selfplay/tournament.cc
- src/selfplay/tournament.h
I'm not entirely happy with the selfplay changes. Any suggestions for improvement are welcome.
Also it isn't very easy to test this interactively, since time is running while you type. The best way is to write some uci commands in a text editor and paste them as a bloc, something like:
```
position startpos
go movetime 1000
```
> remove movetime from limits

- appveyor.yml
- src/benchmark/benchmark.cc
- src/chess/board.cc
- src/chess/board.h
- src/chess/board_test.cc
- src/engine.cc
- src/neural/encoder.cc
- src/neural/encoder_test.cc
- src/selfplay/game.cc
This is in two parts, first moves kStartBoardPos to ChessBoard and second sets Appveyor to always build with WholeProgramOptimization to avoid failing to notice tings like this before the release.
> Fix EncodePositionForNN test failure

- src/mcts/search.cc
(It measures slighly wrong time from what was intended)
> Do not show warning when ComputeBlocking() takes too much time.

- src/neural/opencl/OpenCLTuner.cc
Tuner always loaded the first tuning even if it had wrong parameters.
> Fix OpenCL tuner always loading the first saved tuning

- src/mcts/search.cc
This fixes the hang I reported in #500.
> use bestmove_is_sent_ for Search::IsSearchActive()

- meson.build
- src/neural/opencl/OpenCL.cc
- src/neural/opencl/OpenCL.h
- src/neural/opencl/OpenCLBuffers.cc
- src/neural/opencl/OpenCLBuffers.h
- src/neural/opencl/network_opencl.cc
The per-thread OpenCL resources (OpenCL command queue and buffers) were under `thread_local` management.  When the search threads were created/destroyed, so were these resources, including the OpenCL command queue. Under some architectures, the ASAN (the address sanitiser) reported that destroying the OpenCL command queue was corrupting memory.
This pull request replaces the `thread_local` with a resource pool. The resources will be recycled between threads and the OpenCL command queues never destroyed.
It should fix crashes reported in these issues:
https://github.com/LeelaChessZero/lc0/issues/98
https://github.com/LeelaChessZero/lc0/issues/126
https://github.com/LeelaChessZero/lc0/issues/500
https://github.com/LeelaChessZero/lc0/issues/507
> OpenCL: replace thread_local with a resource pool.

- src/engine.cc
Fixes the following (thanks to va on discord for report):
```
_
|   _ | |
|_ |_ |_| v0.20.0-dev built Nov 20 2018
go nodes 1000
error Network weights file not found.
go nodes 1000
Segmentation fault (core dumped)
```
> fix segv on second go if network not found

- README.md
Fixes the following error when pkg-config is not already installed.
Found Pkg-config: NO
meson.build:368:2: ERROR: Pkg-config not found.
> Install pkg-config

- src/mcts/search.cc
The only case where `SendUciInfo()` can fail the check of `current_best_edge_` is right before printing `bestmove`. However the spec specifies that info should always be output before `bestmove`. This closes #518.
> always print info before bestmove

- src/mcts/search.cc
Winboard with polyglot, when stopping pondering, sends the `position` command very quickly after `stop` and then sends `go` while at the same time waiting for `bestmove` before continuing. This leads to time losses: In some cases lc0 doesn't send `bestmove` at all when stopping, so the one sent after the final `go` is taken to be the one after `stop` and both sides end up waiting until time runs out.
This ensures that a `bestmove` will always be sent when stopping the search (provided `ok_to_respond_bestmove_` is true).
> ensure bestmove is sent when aborting search

- src/engine.cc
- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
Cpuct 3.4 -> 3.0 for play
Cpuct 1.25 -> back to 1.2 for training
Introduce CpuctFactor parameter (2 for play, 0 for training), because we have larger value space (-1..1) than alphazero (0..1)
Cut a few zeros in max CpuctBase value (went above what float could represent)
Minimal value for CpuctBase is now 1, not 0.
> Rework Cpuct related params.

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
Introduce
--temp-cutoff-move (default: 0, i.e. switched off).
Starting from the move specified in this parameter, the temperature is taken from --temp-endgame param.
--temp-value-cutoff
When selecting move using temperature, only consider moves within X% (1% = 0.02 of Q value) from bestmove. Default is 100%, e.g. all moves.
FPU:
--fpu-strategy  Can be "reduction" (as before, value is taken from --fpu-reduction flag) or "absolute" (value is taken from --fpu-value flag)
> Temperature and FPU related params.

- README.md
The readme refers to " the release branch" but no branch with that name exists.
> Fix readme referencing non existent branch

- meson.build
This can only be overridden by doing `meson configure -Db_lto=false` in the build directory. Not a big problem in my opinion, but worth noting.
> lto on by default

- appveyor.yml
Tests by @ankan-ban show it to be consistently faster than the previous version we were using. This may cause trouble next time appveyor updates the vs2017 image since the cuda headers still have compiler version checks. [This post](https://blogs.msdn.microsoft.com/vcblog/2018/10/01/cuda-10-is-now-available-with-support-for-the-latest-visual-studio-2017-versions/) in the "Visual C++ Team Blog" states that "CUDA 10.0 will work with all the past and future updates of Visual Studio 2017" so let's see how this turns out.
> Make appyeyor use the vs2017 compiler.

- appveyor.yml
Using `lc0 benchmark` with the random backend for profile generation was found to lead to faster pgo executables than the usual lto builds. Unfortunately, doing this takes an extra couple of minutes so this patch only adds it for the release builds.
>  pgo build on release 

- README.md
Basic git clone instructions were broken since move to release/x.xx versioning format
> Fixed README for new versioning structure

- build.sh
`build.sh` is calling `ninja` directly, but `meson` also looks for alternatives `ninja-build` or `samu`. This parses (ha) the log file generated to see which one was actually detected. This came up in centos where the default one is `ninja-build`.
> use the ninja detected by meson

- build.sh
Older versions of meson (before 0.46) do not support `--buildtype` and `--prefix` with `meson configure`, e.g. see https://github.com/mesonbuild/meson/issues/969. Similarly seems the initial `meson` did not support the `-Dbuildtype=` and `-Dprefix=` form so we should use different syntax in `build.sh` for the two cases.
> support 'meson configure' with older versions of meson

- src/neural/opencl/OpenCLTuner.cc
Old reference calculated transposed output, new one calculates
non-transposed. Removes transpose from compare.
Fixes #588.
> Fix OpenCL tuner compare function

- meson.build
- src/mcts/search.cc
- src/utils/fastmath.h
This uses fast approximations to calculate log and pow in search. Mainly for discussion.
The approximations used are:
log2(2^N * (1 + f)) ~ N + f 
2^(N + f) ~ 2^N * (1 + f)
N is the integer and f the fractional part, f>=0.
The absolute error of the above approximations for f in [0,1] is less than 0.08.
Better approximations (not tested) are:
log2(2^N * (1 + f)) ~ N + f * (1.34267 - 0.342671 * f)
2^(N + f) ~ 2^N*(1 + f * (0.656366 + 0.343634 * f))
Those are chosen to have zero error for f=0 and f=1 so that there are no discontinuities (also true for the simple ones).
> use fast log and pow approximations

- src/chess/board.cc
- src/chess/board.h
- src/chess/position.cc
Some minor changes to `src/chess/board.{h,cc}`
If I am not mistaken, `ChessBoard::GenerateLegalMovesAndPositions` is not used anymore? Can this be removed or is it still present to cross-check some possible future optimizations of `IsLegalMove` used in `ChessBoard::GenerateLegalMoves`?
> Minor changes to `src/chess`

- meson.build
This reverts #581: lto builds in linux seem to be causing some trouble, so better disable it for now until we can understand what is happening.
> no lto builds by default

- src/utils/fastmath.h
The undefined behavior in FastPow2 is presumably safe as this fix results in no changes to the generated assembly with gcc 8.1. The use of int in FastLog2 was a remnant of a previous iteration, now (u)int32_t is used consistently.
> fix fastmath.h undefined behavior and clean it up

- src/neural/loader.cc
Also fixes the endianness assumption in that code. Closes #639. Checked that both gcc and clang do the right thing with this code on x86_64, at least with -O2.
> fix undefined behavior in DiscoverWeightsFile()

- src/utils/cache.h
Short circuit: do nothing if there is nothing to do.
lc0.exe benchmark --nodes=10000000 --backend=random -t 4
Benchmark final time 52.9688s calculating 186011 nodes per second.
lc0.exe benchmark --nodes=10000000 --backend=random --nncache=0 -t 4
Benchmark final time 45.2008s calculating 220642 nodes per second.
> Check for zero capacity in cache

- src/engine.cc
- src/mcts/search.cc
This fixes #651.
- A search deadline is not set on `go ponder movetime`
- Search::Abort() checks for !bestmove_is_sent_ and not only for stop_ to exit if ponderhit is received after a search limit is reached.
> Fix issues with pondering and search limits.

- src/chess/board.cc
- src/chess/board.h
Various movegen optimizations centered around the introduction of precomputed *king attack info* (attacking lines, pinned pieces, double check detection) that is used to speedup several parts of legal move detection (for all moves).
Unconditional speedup for random backend up to 6% (tested with LTO builds on Linux Fedora 29 64-bit, `gcc 8.2.1`).
The following measurements all share the command line `lc0 benchmark --backend=random --smart-pruning-factor=0 --nodes=1000000 --nncache=1000000`. A 95% confidence interval for the average of the last reported nps value over 25 runs is given for the starting position, the opening position https://lichess.org/editor/rn2kb1r/pp3ppp/2p1pnb1/8/3P1N1q/4B1N1/PPPQ1PPP/R3KB1R_b_KQkq_-_5_9 and the endgame position …
> Movegen speedup via king attack info

- meson.build
While we investigate clang related crashes further.
> Remove ffast-math from the default flags

- src/mcts/search.cc
The previous fix for #651 (#658) made the problem fixed by #539 reappear. The issue is that `stop_` is set when reaching a limit so a `ponderhit` after that (with the original code) will not set `bestmove_is_sent_` that is needed for the search to exit. #658 was also checking if `bestmove_is_sent_` is not set but this allows a race when `Abort` is called too fast after `Stop` and the `bestmove` reply is not sent, thus confusing uci hosts that expect one. This patch adds a check that `ok_to_respond_bestmove_` (that is set by `Stop`) is not set, thus avoiding this race.
> better fix for issue 651

- src/mcts/search.cc
This is an alternative to #629 (suggested by @mooskagh) that disables multivisits for terminal nodes.
> no terminal multivisits

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
r?@Tilps or @jjoshua2?  This limits the winning moves to those with the smallest DTZ. This can lead to sub-optimal moves that aren’t fastest mating sequence, so it’s like the behavior of WDL where it favors pawn pushes and piece sacrifice. This just enforces forward progress instead of moving the king into a corner and shuffling other pieces around.
Here’s a move 124 position from CCC 4 lc0 32742 vs komodo (game 95) that ended up finishing on move 180. With this PR, even if the network somehow ended up favoring the suboptimal moves including sacrificing the bishop, the filtered moves would force a checkmate here in 14 moves (instead of the 56 that it took and worse than the optimal 6 moves).
https://lichess.org/analysis/standard/Q7/8/8/8/2B5/2K1k2p/8/8_w_-_-_0_124
```
position fen …
```
> Favor winning moves that minimize DTZ to reduce shuffling by assuming repeated position by default

- src/syzygy/syzygy.cc
Check that Syzygy tablebase file sizes modulo 64 are 16 as a simple check for corruption.
Inspired by a [Stockfish PR](https://github.com/official-stockfish/Stockfish/commit/bb843a00c1ef381162dc9c2491b5436b6cf5563f) by vondele.
> Check Syzygy tablebase file sizes for corruption

- meson.build
This allows to override the nvcc used by default, if you have multiple cuda versions installed.
> search for nvcc on the path first

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/mcts/search.h
Primarily for Issue #684 but could be interesting to use a super small value for real games to 'give up' search and save time for other moves with more useful search in cases where there are equal options that mean the existing pruning logic can't fire.
Looking for candidate values for training I have tested averaging interval of 100 - and threshold of 5e-6.  With a current T40 net average nodes is about 900, but 1600 for a very early net (although I only gathered a very small amount of data to start).  Which probably makes sense - as nets mature more of the time they know the right search so it converges in agreement with the existing policy quickly.  But there are still outliers which get a lot more nodes.
I have not done any investigation of whether the threshold is actually 'good' but …
> Add option for doing kldgain thresholding rather than absolute visit limiting.

- README.md
I've make a repo
https://github.com/vochicong/lc0-docker
that help you easily run the latest versions of lc0 and the client under docker.
Both CPU and GPU versions are available.
> Easily run latest releases of lc0 and client using NVIDIA docker

- src/neural/network_random.cc
As per the a0 pseudocode - they seed using a uniform backend that returns draw for every position and equal weighting to all policies.
> Add a uniform output option for random backend to support a0 type seed data.

- src/neural/cuda/layers.cc
The index calculations all had c and hw switched.
Before start position with net 50001 was completely different policy between fp16 and non-fp16 - also Exa found that it crashed on linux.
After fix: cudnn at top fp16 below.
info string e2e4  (322 ) N:      45 (+15) (P:  4.70%) (Q:  0.00426) (D:  0.039) (U: 0.07718) (Q+U:  0.08144) (V:  0.0051)
info string f2f4  (351 ) N:      45 (+15) (P:  4.79%) (Q:  0.00444) (D:  0.037) (U: 0.07858) (Q+U:  0.08302) (V:  0.0051)
info string g2g4  (378 ) N:      46 (+14) (P:  4.86%) (Q:  0.00157) (D:  0.036) (U: 0.07971) (Q+U:  0.08128) (V:  0.0063)
info string e2e3  (317 ) N:      47 (+11) (P:  4.80%) (Q:  0.00345) (D:  0.037) (U: 0.08155) (Q+U:  0.08501) (V:  0.0063)
info string h2h4  (403 ) N:      48 (+13) (P:  5.12%) (Q: -0.00255) (D:  0.036) (U: …
> Fix c hw switching in cudnn-fp16 mode with convolution policy head.

- .gitignore
- src/selfplay/loop.cc
Informative Tournament Stats improves display of selfplay stats::
before:
```
tournamentstatus win 3 3 lose 5 3 draw 8 10
```
after - obviously not same tournament as above ;-):
```
tournamentstatus P1: +815 -825 =1213 Win: 49.82% Elo: -1.22 LOS: 40.25% P1-W: +473 -354 =600 P1-B: +342 -471 =613
```
> Informative Tournament Stats - Part 1 of PR487

- src/benchmark/benchmark.cc
- src/engine.cc
- src/selfplay/loop.cc
- src/selfplay/tournament.cc
Rearrange option initialization, so that the help text for mode specific options is printed last.
> put mode specific options last

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
Use this magic combination of UCI parameters to print out our raw values periodically in addition to the UCI standard ones. I'd like to use this mode for my lc0_analyzer.py script, I think others could find it useful too.
This seems intuitive enough to avoid yet another UCI param, because if they have VerboseStats on and a large MultiPv value they probably want to see as much information as possible.
> SendMovesStats on every info update.

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/selfplay/tournament.cc
r?@mooskagh ~Wasn't sure if this should be conditional on self-play / noise. Or if it needs another param -- without, the logic simplifies a little bit.~ ~Edit: Added `fpu-strategy=root-absolute` to do absolute at root and reduction otherwise. Self-play maintains current previous default `fpu-strategy=reduction` and still sets `fpu-reduction=0`, so that's unaffected by the code simplification of not checking noise (but would prevent wanting to use reduction with noise except at root -- do we want to keep that?). To turn on new behavior for training, server would set `fpu-strategy=root-absolute` (with `fpu-value=1 fpu-reduction=0` still set on the client). Added `--early-root-widening` flag which changes FPU behavior at root only for search (leaving verbose, temperature, other `GetFPU` …
> Add AtRoot versions of FpuStrategy and FpuValue (and convert FpuReduction to FpuValue).

- src/mcts/search.cc
Fixes following compiler warnings (gcc 8.3.1):
```[22/114] Compiling C++ object 'lc0@exe/src_mcts_search.cc.o'.
../../src/mcts/search.cc: In member function ‘void lczero::Search::UpdateKLDGain()’:
../../src/mcts/search.cc:330:25: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<unsigned int>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
for (int i = 0; i < new_visits.size(); i++) {
~~^~~~~~~~~~~~~~~~~~~
../../src/mcts/search.cc:335:25: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<unsigned int>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
for (int i = 0; i < new_visits.size(); i++) {
~~^~~~~~~~~~~~~~~~~~~
```
> Fix unsafe comparisons.

- src/mcts/params.cc
r?@mooskagh Cleans up the text and makes the range symmetrical.
@jkormu wanted to test with an offset of -1 but couldn't https://github.com/LeelaChessZero/lc0/pull/750#issuecomment-468019066, and #technical had some confusion about whether the offset should be negative or not.
> Update TempVisitOffset help text and allowed values.

- src/chess/board.cc
The illegal moves are removed from the MoveList returned by GeneratePseudolegalMoves().
Avoiding the allocation of a second MoveList makes the function faster.
> Improve the speed of ChessBoard::GenerateLegalMoves

- src/neural/opencl/network_opencl.cc
I confess I am uncertain as to why the hard limit was previously set to the default, 16, but I have found that on Mac and with an AMD Vega 56, an OpenCL batch_size of 32 works perfectly well and is about 10% faster than batch_size 16.
I have left the default batch_size unchanged.
> Increased hard limit on batch size in opencl backend to 32

- src/selfplay/loop.cc
- src/selfplay/loop.h
- src/selfplay/tournament.cc
- src/selfplay/tournament.h
Doesn't stop any games in progress as opposed to quit which terminates the app.
If we want to really aggressively go after short game bias we would also need to ensure each thread plays the same number of games, but at least with this in place we can look at migrating the client to use interactive mode to reduce short game bias.  Every thread same number of games could be another flag in future.
> Add stop command to selfplay interactive mode to allow for graceful exit.

- src/mcts/search.cc
r?@mooskagh or @Tilps I just noticed from CCC 7 that lc0 would have eval drop from winning to 0 sometimes. This is because there was only one TB-allowed move, so search stops before finishing a visit to any edge. So just use the root eval as an estimate instead of 0.
E.g., 1418 lc0 vs wasp with one dtz minimizing move
```
position fen 3Q4/8/8/4K3/Q7/8/5k2/8 w - - 1 110
go nodes 100
info depth 1 seldepth 1 time 34 nodes 1 score cp 0 hashfull 0 nps 29 tbhits 2 pv d8d2 f2g1
info depth 1 seldepth 1 time 120 nodes 1 score cp 6923 hashfull 0 nps 8 tbhits 2 pv d8d2 f2g1
```
and 1425 senpai vs lc0 with one winning move
```
position fen 8/7P/6K1/8/5P2/1b4k1/7r/8 b - - 2 91
go nodes 100
info depth 1 seldepth 1 time 132 nodes 1 score cp 0 hashfull 0 nps 7 tbhits 2 pv b3c2 g6g7
info depth 1 seldepth …
```
> Use parent Q as a default score instead of 0 for unvisited pv.

- src/mcts/node.cc
- src/mcts/node.h
- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/mcts/search.h
r?@mooskagh Not as feature-full as #700, but this behaves more like TB terminals. Convert a node when search notices children have terminal behavior so future search can stop sooner. Slight refactoring of NodeToProcess to as TerminalHit behaved the same as Extension(1).
Example:
```
./lc0 -w 11258 --verbose-move-stats --fpu-strategy-at-root=absolute --minibatch-size=1 --smart-pruning-factor=0
position fen 3k4/p4Q2/3N3p/1p1B4/8/1P2P3/2R2PPP/6K1 w - - 1 31 moves f7a7
go nodes 1    
h6h5 N:       0 (+ 0) (P: 47.68%) (Q:  1.00000) (V:  -.----)
b5b4 N:       0 (+ 0) (P: 52.32%) (Q:  1.00000) (V:  -.----)
go nodes 2
h6h5 N:       1 (+ 0) (P: 47.68%) (Q: -0.97491) (V: -0.9749)
b5b4 N:       1 (+ 0) (P: 52.32%) (Q: -0.97261) (V: -0.9726)
go nodes 3
h6h5 N:       1 (+ 0) (P: 47.68%) (Q: -0.97491) …
```
> Also make parents Terminal if any move is a win or all moves are loss or draw.

- src/mcts/params.cc
- src/mcts/search.cc
It is widely agreed that Leela's eval in centipawns is inflated and a headache to viewers in tournaments such as TCEC and CCC. It has led some to believe that Leela "is just too optimistic" or "overestimates positions", or that high evals "is just a characteristic of neural networks". Furthermore, it has made the TCEC and CCC adjudication rules less reliable. All of this can be resolved by a slight tweak to the conversion formula.
The process that led to the current formula `290.680623072 * tan(1.548090806 * Q)` is as follows:
- Evals of Stockfish and Leela (Apr/15/2018) were obtained by removing pieces from the starting position
- Based on correlation analysis, `300 * tan(1.5 * Q)` was found to be a close predictor of SF's eval
- It was agreed to use tan() over logit due to its flatter …
> Recalibrate centipawn formula

- README.md
Some help requests originated from people downloading the 0.19 release branch, following the instructions. The updated links will get the latest code from the release/0.21 branch in every case.
Note that I couldn't find a github api to get the latest release zip and tar, so the links point to the head of the release/0.21 branch (like the `git clone` command).
> update download links in README

- build.sh
Hmm I'm not entirely sure this is right. I'm rather new at doing bash commands.
This was intended to stack directories and enable one to do a remote execution of this shell script into build.sh.
Almost all credit to borg.
> Add pushd command in build.sh

- src/neural/blas/network_blas.cc
- src/neural/blas/winograd_convolution3.cc
- src/neural/blas/winograd_convolution3.h
https://github.com/LeelaChessZero/lc0/pull/864 was the previous attempt at this, but not strictly correct (although working in practice by allocating more than needed).
> Correct allocation size of M matrix in Winograd convolution

- src/mcts/search.cc
r?@mooskagh Alternative to #879 Followup to https://github.com/LeelaChessZero/lc0/pull/860#issuecomment-500189165
before:
```
position fen r2qk2r/ppp2p2/3p4/2b1p1pp/2BnP1nP/3P1PB1/PPP3P1/RN1Q1RK1 b kq - 0 13 moves d4e2
go nodes 2
info depth 2 seldepth 3 time 20 nodes 257 score cp -12799 hashfull 0 nps 12850 tbhits 0 pv g1h1 e2g3
position fen r2qk2r/ppp2p2/3p4/2b1p1pp/2BnP1nP/3P1PB1/PPP3P1/RN1Q1RK1 b kq - 0 13 moves d4e2 g1h1
go nodes 2
info depth 1 seldepth 2 time 50 nodes 123 score cp 12799 hashfull 0 nps 2460 tbhits 0 pv e2g3
```
after:
```
position fen r2qk2r/ppp2p2/3p4/2b1p1pp/2BnP1nP/3P1PB1/PPP3P1/RN1Q1RK1 b kq - 0 13 moves d4e2
go nodes 2
info depth 2 seldepth 3 time 0 nodes 77 score cp -12800 hashfull 0 nps 0 tbhits 0 pv g1h1 e2g3
position fen …
```
> Divide by a slightly smaller divisor to truncate to +/-12800.

- src/mcts/search.cc
r?@mooskagh The current implementation didn't seem like it supports AlphaZero's `by softmax sam- pling with a temperature of 10.0 among moves for which the value was no more than 1% away from the best move for the first 30 plies`
In particular, a random single visit with high eval towards the end of limited node search could prevent selecting moves that got more visits.
> Use the best move eval instead of highest eval for temperature cutoff.

- src/mcts/node.cc
Set probabilities for illegal moves in a loop instead of using std::memset.
`std::memset(result.probabilities, -1, sizeof(result.probabilities));` is setting all bytes in `result.probabilites` as `0xffffffff`.
> Set probabilities for illegal moves in a loop

- src/mcts/search.cc
r?@mooskagh or @Tilps Fix a crash for FEN with no move history and no moves.
before
```
position fen 8/8/8/8/8/8/8/8 w - - 0 1
go nodes 1
Segmentation fault: 11
position fen 8/8/8/8/8/8/8/8 w - - 0 1 moves a1a1
go nodes 1
bestmove a1a1
```
after
```
position fen 8/8/8/8/8/8/8/8 w - - 0 1
go nodes 1
bestmove a1a1
position fen 8/8/8/8/8/8/8/8 w - - 0 1 moves a1a1
go nodes 1
bestmove a1a1
```
> Check for null parent in search backup.

- appveyor.yml
- meson.build
Due to a meson bug, we were forced to compile on windows using the `/MD` switch unconditionally. This bug was fixed for the 0.51 meson release (https://github.com/mesonbuild/meson/pull/5454), breaking our appveyor builds.
> Fix appveyor breakage due to meson fix.

- src/mcts/search.cc
- src/neural/blas/network_blas.cc
- src/neural/cuda/network_cudnn.cc
- src/neural/network_random.cc
- src/neural/network_tf.cc
- src/neural/opencl/network_opencl.cc
- src/utils/fastmath.h
Perform policy softmax outside backends on set of legal moves.
This should fix the limited accuracy issues observed with CUDA backend FP16 in combination with policy masking enabled in training.
Blas backend has been tested.
Testing of CUDA and OpenCL backend much appreciated!
> Fix policy softmax accuracy if masking is enabled.

- meson.build
- src/version.cc
- src/version.h
Add unique git short revision to version string. Turns
```
_
|   _ | |
|_ |_ |_| v0.23.0-dev built Aug  8 2019
```
into:
```
_
|   _ | |
|_ |_ |_| v0.23.0-dev+gad71ed0 built Aug  9 2019
```
Very handy to avoid any confusion during development/benchmarks/comparison of PRs/logs used for future reference.
> Add git short revision to version string.

- src/utils/fastmath.h
The initial fastmath.h functions were optimized analytically to minimize rms error over the full mantissa range. Unfortunately, this was not taking into account the limited float32 accuracy, resulting in a small offset from the desired values. Here I used a numerical optimization approach to tune the constants for minimal error over the full mantissa range, and took the opportunity to minimize max error instead of rms error.
Also improved the comments a bit.
> minimize max fastmath error considering float32 accuracy

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/selfplay/tournament.cc
In preparation for experiments adjusting some magic numbers from A0-chess (α = 0.3, ε = 0.25), we can add options for the server to control these values. ~NB: with `--noise` replaced by `--noise-epsilon`, existing commands that use the old option will fail: `Unknown command line flag: --noise.`~
```
./lc0 --show-hidden --help
-n,  --[no-]noise
Add Dirichlet noise to root node prior probabilities. This allows the engine to
discover new ideas during training by exploring moves which are known to be bad.
Not normally used during play.
[UCI: DirichletNoise  DEFAULT: false]
--noise-epsilon=0.00..1.00
Amount of Dirichlet noise to combine with root priors. This allows the engine to
discover new ideas during training by exploring moves which are known to be bad.
Not normally used during play. …
```
> Add hidden options for controlling Dirichlet noise Alpha and Epsilon.

- meson.build
This commit solves a problem with building lc0 from sources on macOS Mojave 10.14.6:
$ meson mkl1 --buildtype=release -Ddefault_library=static
The Meson build system
Version: 0.51.1
Source dir: /Users/andreas/projects/lc0
Build dir: /Users/andreas/projects/lc0/mkl1
Build type: native build
DEPRECATION: Option uses prefix "build_", which is reserved for Meson. This will become an error in the future.
Project name: lc0
Project version: undefined
C++ compiler for the build machine: c++ (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
C++ compiler for the host machine: c++ (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library libprotobuf found: NO
Found pkg-config: /usr/local/bin/pkg-config (0.29.2) …
> Fix macOS meson.build

- src/mcts/search.cc
r?@mooskagh Similar to https://github.com/LeelaChessZero/lc0/commit/82b3f208d33fac38c768f2ad2bd4d45c30599fa9 which fixed `go infinite searchmoves a2a4`… this commit fixes it for `go nodes 100 searchmoves a2a4` where in both cases, the intent of searchmoves is to have search focus on the desired move, so the `possible_moves` short-circuit behavior is undesired.
Before:
```
go nodes 100 searchmoves a2a4
info string a2a4  (207 ) N:       0 (+ 1) (P:  2.42%) (Q:  0.08519) (D:  0.000) (U: 0.03634) (Q+U:  0.12152) (V:  -.----) 
bestmove a2a4 ponder g8f6
```
After:
```
go nodes 100 searchmoves a2a4
info string a2a4  (207 ) N:     108 (+ 9) (P:  2.42%) (Q: -0.05578) (D:  0.000) (U: 0.00642) (Q+U: -0.04936) (V: -0.0646) 
bestmove a2a4 ponder h7h5
```
(One of my use cases is `go nodes 2 searchmoves …
> Only short-circuit search with a non-0 SmartPruningFactor.

- src/mcts/search.cc
- src/mcts/search.h
- src/selfplay/game.cc
- src/selfplay/game.h
- src/selfplay/tournament.cc
- src/selfplay/tournament.h
Adds two parameters to selfplay.
--minimum-allowed-visits - integer parameter that causes selfplay to discard selected temperature moves that are not best and are less than the limit.
--discarded-start-chance - floating parameter in 0 to 100, that is the percentage chance that a game will attempt to start from the position after a discarded move - if there are any such games that have not yet been played.
Discarded game positions are selected from at random.  In almost every scenario that minimum-allowed-visits is greater than 1 it is likely that the discard pile will grow continuously.  Thus I have put in a hard coded cap to avoid it growing without bound.  I hard coded it as I don't think it will need tuning.
> Badgame split

- src/chess/callbacks.h
- src/selfplay/loop.cc
- src/selfplay/tournament.cc
This will allow client to add a pgn move annotation to the last ply of the 'opening' so people can know when the training data actually starts.
> Record how many ply in the gameready move output are from before net play starts.

- src/neural/loader.cc
"Fat Fritz" weights file is fully compatible with Lc0, but has poor minimal version signature.
Whitelist it for Lc0 to be able to use that file.
> Network compatibility.

- appveyor.yml
Appveyor will keep it around for 6 months and can be used to debug issues with generated binaries.
> generate (and retain) pdb file

- appveyor.yml
Something changed in the appveyor string parsing and now we need %%%% inside double quotes to get a single % to the command instead of the old %%.
> appyeyor now needs more %% in strings

- src/neural/cuda/network_cudnn.cc
@jjoshua2 mentioned on <https://github.com/LeelaChessZero/lc0/pull/849#issuecomment-529213807> that nvidia jetson with compute capability 5.3 has fast fp16 performance. A web search suggests this is also true for jetson tx2 with compute capability 6.2, so the relevant check is updated.
> allow using cudnn-fp16 on jetson

- src/utils/filesystem.h
- src/utils/filesystem.posix.cc
- src/utils/filesystem.win32.cc
This is for #976, providing access functions to get the users cache, config and data directories using the `$XDG_*` environment variables, or system specific alternatives. An empty string is returned on windows or when no alternative can be provided.
> get system specific directories

- subprojects/gtest.wrap
This will be needed for building with c++17 on windows: at least appveyor builds fail with the previous version.
> update gtest wrap to 1.8.1 rev. 1

- src/chess/board.cc
- src/chess/board_test.cc
r?@mooskagh or @borg323 Wasn't sure if it's preferable to do `this->rooks()` vs `ChessBoard::rooks()` or just have a different local variable name.
> Use actual rooks instead of rook-like pieces when determining castling.

- src/mcts/stoppers/stoppers.h
r?@mooskagh or @borg323. @Tilps noticed `prev_child_nodes_` was uninitialized, so if it was negative, the condition to exit early would be not be satisfied:
https://github.com/LeelaChessZero/lc0/blob/7eb26031c56e27e66d7fdf54afd4aaa98b41acdc/src/mcts/stoppers/stoppers.cc#L150
This results in saving the nodes and visits for subsequent stop checks. If the new child nodes was 0 while saving visits, when the next time the condition to exit early is also skipped (e.g., 100 new nodes with default average_interval), this resulted in the division by 0.
> Initialize prev_child_nodes_ to prevent storing of visits without new child nodes.

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
r?@mooskagh This also allows showing the default single primary pv with actual nodes visited to that child. Also very small factoring out `params_.GetMultiPv()` to avoid calling per loop and reuse the initial call at the very top of `SendUciInfo`.
@jjoshua2 Looks like you were asking for this last week:
> it appears multipv outputs total node count
is there a way to get to print multipv node count?
could that be a simple flag im missing? or simple source code change? or do we not even keep track of that?
Before:
```
--multipv=5
go nodes 40
info depth 4 seldepth 11 time 6998 nodes 39 score cp 30 hashfull 1 nps 5 tbhits 0 multipv 1 pv e2e4 c7c6 d2d3 g8f6 g1f3 d7d6
info depth 4 seldepth 11 time 6998 nodes 39 score cp 20 hashfull 1 nps 5 tbhits 0 multipv 2 pv d2d4 g8f6 c2c4 e7e6 g2g3 f8b4 …
```
> Allow showing per-pv node counts instead of total nodes.

- appveyor.yml
This reverts commit 0a4fdddd66decf78dfccecc05f702da587314071 (#978). 
Appveyor seems to have changed the behavior of % in strings back to what it was before.
> Revert "appyeyor now needs more %% in strings (#978)"

- src/mcts/stoppers/stoppers.cc
- src/mcts/stoppers/stoppers.h
r?@mooskagh or @borg323 or @Tilps Fix #1003 by pre-casting nodes and min_gain to `float` to avoid 2 problems:
These two divisions are integer divisions with the integer 0 result casted to float:
https://github.com/LeelaChessZero/lc0/blob/b7f67acd8b15782b82d770186fa7a65586b1b8b5/src/mcts/stoppers/stoppers.cc#L156-L157
And the comparison against min_gain was always against 0 unless `min_gain` was set to 1:
https://github.com/LeelaChessZero/lc0/blob/b7f67acd8b15782b82d770186fa7a65586b1b8b5/src/mcts/stoppers/stoppers.cc#L160
I realize nodes aren't a float, so the alternative is to `prev_visits_[i] / static_cast<float>(prev_child_nodes_)` or maybe cast outside the `for` loop?
> Use floats for KLD-related division expressions.

- src/chess/board.cc
- src/chess/board.h
- src/engine.cc
- src/mcts/node.cc
(also do that when unvisited move is entered through uci position command, but it worked fine without that too)
Fixes #1001
> Convert moves to FRC-compatible encoding when building searchmoves list.

- src/engine.cc
- src/engine.h
- src/mcts/search.cc
- src/mcts/search.h
1. Reset move clock on `go` command if there was no ucinewgame or
position before it.
2. For nps, only start timer after the first iteration is done.
Fixes #1012
> Fix time reporting issues.

- src/neural/opencl/clsource/se.opencl
For large batch size and big SE-unit fully connected layer the `fc_out` variable can exceed the constant memory limit.
> Remove __constant in apply_se

- meson.build
We are adding an opencl dependency even when not building the opencl backend. While this should have been harmless, a recent meson bug causes build failures on a mac, even with `-Dopencl=false`.
> fix opencl=false build on mac

- appveyor.yml
- scripts/check_opencl.bat
This makes sure the appveyor opencl build also has blas compiled in (with eigen) and adds a batch file to do a sanity check of the opencl driver (using the check backend)
> add check_opencl batch file

- meson.build
Setting the warning level to 3 increases the msvc warnings 5-6 times. Maybe we should disable some?
> fix various meson warnings

- subprojects/eigen.wrap
- subprojects/gtest.wrap
- subprojects/zlib.wrap
From https://github.com/mesonbuild/meson/issues/6446 I get the impression fixing wrapdb will take longer than I was hoping.
> bypass wrapdb

- appveyor.yml
- scripts/check_dx.bat
- src/neural/network_check.cc
Adds a check_dx batch file similar to check_opencl to check driver accuracy, as there are apparently some bad ones out there. The accuracy limit was determined experimentally with the help of @ankan-ban.  
In the process we also discovered the check backend was reporting relative as absolute accuracy and vice versa.
Finally, during testing I found pgo builds of the dx backend are not working, probably due to a missing driver in the appveyor vm.
> add check_dx batch file

- meson_options.txt
This has been reported a few times on discord, so adding the path to the defaults.
> Some cuda installations use /usr/lib/cuda

- appveyor.yml
Need to change the network download link after the site changes. This was cached, so we didn't notice earlier.
> appveyor fix for training.lczero.org

- src/mcts/stoppers/stoppers.cc
This appears to have been a regression in the time code refactor.
This is potentially not an identical match for the original behavior, but I'm reasonably confident that it is a good match in all the ways that matter.
Without this fix it is possible that watchdog will terminate search based on an estimate of 1.5k nps (or lower) calculated in smart pruning stopper based on 0 actual nodes over 200ms (or higher).
> Ensure not to fully prune before first eval time is set.

- meson.build
There are compilers such as the Android NDK's clang cross-compilers that don't support -march=native. So add a check before adding the flag.
> meson, only add -march=native if compiler supports it.

- meson.build
Android's `libc, bionic`, provide built-in support for `pthreads`, so no additional linking is necessary.
> meson, don't link pthread when host is Android.

- appveyor.yml
The old wildcard would also catch other zip files that may have been downloaded during setup if the cache was invalidated prior to the release.
> stricter appveyor artifacts wildcard

- src/mcts/node.h
Node size was increased in #961, but this assert was not changed.
> Increase 32-bit node size in assert

- src/chess/callbacks.h
- src/chess/uciloop.cc
- src/engine.cc
- src/mcts/node.cc
- src/mcts/node.h
- src/mcts/search.cc
r?@mooskagh or @Ttl Fix #837 by making use of `GetM()` on terminals to not need to traverse the tree calculating mate distance. Track the type of Terminal when extending a node as well as converting ancestors to differently rank and score.
https://lichess.org/analysis/4r2k/2q2Q2/5KRb/8/8/8/8/8_w_-_-_0_1
```
./lc0 -w 59100 -v --multipv=100 --per-pv-counters
position fen 4r2k/2q2Q2/5KRb/8/8/8/8/8 w - - 0 1
go infinite
info nodes 175975 score mate  1 multipv  1 pv g6h6
info nodes 219983 score mate  3 multipv  2 pv f7e8 h6f8 e8f8 h8h7 g6h6
info nodes  53783 score cp 1160 multipv  3 pv f7c7 e8f8 f6e6 f8e8 e6d5 e8e1 c7f7 h6f8 f7g8
…
info nodes     69 score cp -348 multipv 14 pv g6g5 c7d6 f6f5 d6d3 f5f6 d3f3
info nodes     84 score mate -3 multipv 15 pv f7e7 c7e7 f6f5 e7e4 f5f6 e4f4
info nodes …
```
> Prefer shorter winning mates and report mate score.

- meson.build
- meson_options.txt
- src/neural/factory.cc
- src/neural/loader.cc
- src/utils/commandline.cc
This is based on the great work done by @lealgo in <https://github.com/LeelaChessZero/lc0/pull/868>. The main difference is that this version allows embedding after the fact: It looks for a zip file appended at the end of the executable that stores just an uncompressed network file (e.g. one generated by `zip -0`).
> simple network embedding mechanism

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/selfplay/tournament.cc
For low batch sizes most of the batches are not full because there are too many NNCache hits. This change allows changing the limit on how many out of order evals can happen before non-full batch is submitted.
Tests with 128x10 network on startpos 1M nodes with maximum batch size 68, max-collisions 68, max-prefetch=68.
Before there are many non-full batches:
After with bigger max out of order evals limit almost all batches are full:
> Add max out of order evals parameter

- appveyor.yml
- cross-files/armv7a-linux-android
Lowers the API level to 21 (Android 5). Current target is API level 24 (Android 7) which is too high for older armv7-a devices. Like in this issue #1104. The reason it was to high was because of this:
https://android.googlesource.com/platform/bionic/+/master/docs/32-bit-abi.md
> Lower Android API level requirements for armv7-a build.

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/selfplay/tournament.cc
Amount of full batches as function of the maximum out of order evals scales similarly with different maximum batch sizes when it's relative to the maximum batch size. This makes it easier to tune the parameters as batch size and max-out-of-order-evals can be adjusted separately.
> Max out of order evals relative to the maximum batch size

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
As already discussed on Discord after @kiudee posted a tuning result including MLH, the current `MovesLeftScale` parameter from #961 is very hard to interpret. This PR replaces the `MovesLeftScale` parameter with a `MovesLeftSlope` parameter `slope := factor/scale` which gives the direct Q bonus per shorter move, and the maximum effect is capped to `MovesLeftFactor`.
I think this pair of parameters controlling the effect of MLH on search is the combination which on the one hand is the easiest to interpret, and on the other hand is as orthogonal as possible concerning parameter tunings.
> Refactor moves left head parameters into factor and slope

- src/neural/blas/network_blas.cc
Matches cudnn output with the nets I tested with (Some available in #961). Valgrind output also looks clean.
> Moves left head support for blas

- README.md
Update our readme to use references to the latest 0.24 release instead of the older 0.23 release.
> Update references to the newest release

- src/mcts/node.h
- src/mcts/search.cc
Also include a fix draw_score being declared bool in GetBestRootChildWithTemperature.
Basically the same as jio's PR, I just wanted to see what removing the parameter default looked like, so I did it myself...
> Remove default for logit_q parameter to GetQ

- src/chess/board.cc
- src/chess/board.h
kPawnMask sitting in board.cc forces us to write just two of this list of functions in board.cc when the rest of them are in board.h, and it seems like that constant should belong to ChessBoard anyway, since en passant bits in the mask are part of the information requires to understand the contents of the class. Declaring the constant in board.h lets us have a clean block for all of the methods that return these bitboards.
> make pawn mask code slightly less disruptive

- src/chess/board.cc
- src/chess/board.h
- src/chess/pgn.h
- src/neural/encoder.cc
- src/syzygy/syzygy.cc
I looked at this for a long time and haven't been able to find any reason that having two calls, one for their and one for our knights, does anything but make the code a little bit harder to read (specifically because it looks like there must be some reason). This probably isn't central to how anything works but it seems like it wouldn't interfere with what anyone else is doing and makes this easier to follow, unless I'm missing the reason for it.
Similar changes for kings in #1132
Benchmarks:
```
- Master
Benchmark final time 10.0009s calculating 212417 nodes per second.
Benchmark final time 10.0006s calculating 208707 nodes per second.
Benchmark final time 10.0004s calculating 208102 nodes per second.
- Knights
Benchmark final time 10.0005s calculating 208702 nodes per second.
Benchmark …
```
> Match knights() call more cleanly with other piece calls

- src/chess/bitboard.h
- src/chess/board.h
- src/chess/pgn.h
- src/neural/encoder.cc
- src/syzygy/syzygy.cc
same idea as #1131
this also adds an `as_board()` method to BoardSquare to save us from writing `1ULL << *.as_int()` more than once
Benchmarks:
```
- Master
Benchmark final time 10.0009s calculating 212417 nodes per second.
Benchmark final time 10.0006s calculating 208707 nodes per second.
Benchmark final time 10.0004s calculating 208102 nodes per second.
- Knights
Benchmark final time 10.0005s calculating 208702 nodes per second.
Benchmark final time 10.0004s calculating 204465 nodes per second.
Benchmark final time 10.0006s calculating 206022 nodes per second.
- Kings
Benchmark final time 10.0005s calculating 206489 nodes per second.
Benchmark final time 10.0005s calculating 207881 nodes per second.
Benchmark final time 10.0006s calculating 206204 nodes per second.
```
> Match kings() call more cleanly with other piece calls

- src/neural/loader.cc
r?@mooskagh or @Tilps  Fix #1148 by saving the value of `has_network_format` before mutable.
> Remember if network has format before making mutable.

- src/neural/opencl/OpenCL.h
- src/neural/opencl/OpenCLBuffers.cc
- src/neural/opencl/OpenCLBuffers.h
- src/neural/opencl/network_opencl.cc
Output matches cudnn backend. Nets without moves left head still work as before.
> Moves left head for OpenCL backend

- src/mcts/params.cc
- src/mcts/params.h
This reverts commit 1753f7c40332121950f818979d9c71bca34ee230.
Followup to #267 but only commit after https://github.com/LeelaChessZero/lc0/commit/8f13ece9698888e5b156c7b2f3d3300832bda004 `has been included in a version which has been made mandatory.` https://github.com/LeelaChessZero/lc0/pull/267#issuecomment-522185245
> Revert "Restore --noise treating as --noise-epsilon=0.25."

- src/mcts/params.cc
- src/selfplay/tournament.cc
no longer needed as its always sent by training server.
> Remove selfplay override for root has own cpuct params

- src/mcts/node.h
- src/mcts/search.cc
Was wrong in the case that M is non-zero for best.
This new parameterisation saves recomputing 'score - u' for the best node at the cost of an extra store when we get a new best.  I think it'll also help with people remembering to update it correctly as they add or change additional terms other than U as part of the score.
> Fix and simplify GetVisitsToReachU.

- src/mcts/node.cc
Fix a crash introduced in #1164.
> Only clear edge list if all children removed.

- src/mcts/search.cc
- src/mcts/search.h
The idea is any time we're resolving a batch where actual changes to the tree have happened, existing collisions are no longer necessarily useful, and indeed may be a problem, so we should undo them as soon as possible, regardless of which thread used them to gather a batch.
Note this may have a bug where at end of search shared collisions could be left over, I need to add some code to enforce they get cleared out during search destruction.
> Shared collisions.

- README.md
- meson.build
Also update the instructions to indicate Ubuntu 18.04 needs GCC 8 or
later regardless of the clang in use, because clang falls back to the
GCC libstdc++ headers.
Fixes issue #1182.
> Check for presence of charconv headers.

- src/neural/blas/network_blas.cc
- src/neural/cuda/network_cudnn.cc
- src/neural/dx/network_dx.cc
- src/neural/factory.cc
- src/neural/factory.h
- src/neural/loader.cc
- src/neural/network_check.cc
- src/neural/network_demux.cc
- src/neural/network_mux.cc
- src/neural/network_random.cc
- src/neural/network_rr.cc
- src/neural/network_tf_cc.cc
- src/neural/opencl/network_opencl.cc
Changes all backends to make the WeightsFile passed to them optional, with an error if not there in all except random.
Also included is the hack to fix the c++ version incompatibility with tensorflow.
> make it possible to call backend without a net

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
An alternative to #1158.
This should give us some decent number of options for messing around with things to try and get good results for training.
All 3 options are hidden for now.  Can unhide them as needed once we've learned some more in training.
> Add moves left effect scaling factors.

- src/mcts/params.cc
Recent tunes have shown values very close to the maximum as being optimal.  Increase maximum to enable further tuning in future.
> Increase maximum maximum collision events.

- src/mcts/params.cc
Most combinations will be nonsensical, but constant=-0.1 quadratic=1, or something similar, seems like it could make sense, so I just increased the range for all 3.
> Increase possible range for moves left hidden parameters.

- src/mcts/node.cc
r? @mooskagh or @Tilps or @AlexisOlson Renaming the `GetNoCaptureNoPawnPly` added in #1204 to the new name `GetRule50Ply` from #1207.
> Fix merge conflict between #1204 and #1207.

- src/chess/position.cc
- src/chess/position.h
- src/mcts/node.cc
- src/mcts/node.h
- src/mcts/search.cc
- src/mcts/search.h
r?@mooskagh Use more of the Terminal enum to store CantWin and CantLose states that are used in a more generalized parent conversion behavior. Notably, a child draw makes the parent CantWin, and this then makes it possible to decide if choosing among moves that Draw or CantWin (or Loss), the best move is Draw -- thus a new parent Draw Terminal that otherwise wouldn't have been converted before. Additionally, if all possible moves CantWin, the parent is CantLose and grandparent is also CantWin. E.g.,
https://lichess.org/analysis/5Qk1/6b1/6KR/6p1/8/8/8/8_b_-_-_0_1
```
./lc0 -w 591226 -v
position fen 5Qk1/6b1/6KR/6p1/8/8/8/8 b - - 0 1
g7f8 N:     284 (P: 56.96%) (WL: -0.31254) (D:  0.682) (M:  3.7) (L) 
g8f8 N:    4557 (P: 43.04%) (WL: -0.03414) (D:  0.945) (M:  4.6) 
Bxf8 / g7f8 CantWin (L) …
```
> Convert parents that cannot win or cannot lose to help find more draws.

- build.cmd
- build.sh
- meson.build
1. On windows check for `cl` on the path before calling `vcvarsall`, in case it is already set up. Also simplify msbuild calling, this was probably a remnant from vs2015.
2. Still on windows, do not look for a zlib dependency, most likely if one is found it won't be the correct one. In the two cases reported, one was from msys2, and the other was crashing for unknown reasons.
3. In `build.sh`, if meson is not on the path, check for an installation in `~/.local` and add it to the path.
> build improvements

- src/mcts/params.cc
- src/mcts/search.cc
Based on the current TCEC games, the Q to centipawn conversion formula seems to be too pessimistic at high Q. lc0 cp evaluations are often much lower than the other engines.
I downloaded the TCEC SUFI evaluations and compared to the lc0 cp evaluations to SF evaluations. Below are the results:
The evaluation for Q < 0 comes from only one game and can be ignored. The current formula is the line labeled with centipawn. The first too optimistic conversion function is centipawn_2018 line. I also plotted the conversion function from #841 that used the old equation but fitted to more games. The #841 equation seems to fit very well to the median SF evaluation. I can get slightly better fit with more complex functions, but this one has advantage of being easily invertible which is nice for …
> Update q to cp conversion formula

- src/neural/cuda/layers.cc
- src/neural/cuda/layers.h
- src/neural/cuda/network_cudnn.cc
- don't typecast directly to half datatype in CPU side code as older CUDA runtime doesn't support that.
- don't use gemmEx version on GPUs older than Maxwell generation (not supported).
- modify the check to enable custom_winograd setting. It should be faster in most cases - except on RTX GPUs when using fp16.
> cuda winograd fixes

- src/chess/board.cc
- src/chess/board.h
- src/chess/board_test.cc
- src/chess/pgn.h
r? @Tilps or @mooskagh Fen handling already allows some leeway, so this makes it even more generous assuming white to move, ~all castling (including 960)~ no castling, no en passant, 0 rule50ply, 1 total moves.
Before:
```
position fen K1k1r b
go nodes 1
error Bad fen string: K1k1r b
```
After:
```
position fen K1k1r b
go nodes 1
info … multipv 14 pv e8h8
position fen K1k1r b moves c8e8
go nodes 1
info … multipv 2 pv a8b7
```
~Where the last position shows the castling of black and still supporting "moves"~
> Allow most parts of fen to be optional.

- src/chess/uciloop.cc
r? @mooskagh Fix #1176 from `uciloop.cc` to report at least 1 depth as search will always at least visit the search root. Alternative would be updating `search.cc` for both `SendUciInfo` and `MaybeOutputInfo`.
Before:
```
position fen 3k1b1r/3R2pp/3p1n2/pBp1p3/q2B2Q1/2P4P/2P2PP1/6K1 b - - 3 23
go nodes 300
info depth 2 seldepth 7 time 996 nodes 294 score mate -3 nps 2409 tbhits 0 pv d8c8 b5a6 c8b8 d7b7 b8a8 g4c8
position fen 3k1b1r/3R2pp/3p1n2/pBp1p3/q2B2Q1/2P4P/2P2PP1/6K1 b - - 3 23 moves d8c8 b5a6
go nodes 300
info depth 0 seldepth 0 time 0 nodes 300 score mate -2 tbhits 0 pv c8b8 d7b7 b8a8 g4c8
ucinewgame
position fen 3k1b1r/3R2pp/3p1n2/pBp1p3/q2B2Q1/2P4P/2P2PP1/6K1 b - - 3 23 moves d8c8 b5a6
go nodes 300
info depth 1 seldepth 1 time 47 nodes 1 score cp -136 tbhits 0 pv c8b8
```
After: …
> Always report at least 1 depth.

- src/neural/cuda/network_cudnn.cc
don't set CUBLAS_TENSOR_OP_MATH unconditionally.
> Fix un-intended regression in cudnn-fp16 backend running on GTX GPUs

- src/neural/cuda/layers.cc
- src/neural/cuda/layers.h
- src/neural/cuda/network_cudnn.cc
- don't save untransformed weights
- print warning message when low memory is detected.
> memory optimization for cudnn custom_winograd

- src/mcts/search.cc
- src/mcts/search.h
r?@mooskagh or @Tilps I've noticed it's a bit cumbersome to get the Q/V of a position where currently you can get the cp score with `go nodes 1` or you need to have the previous position and `go nodes 2 searchmoves …`. Also when using `--per-pv-counters`, it's tedious to figure out how many total nodes so far and similarly counting up the possible number of moves.
I've added those stats as `node` in verbose output like the children and set the P to be VisitedPolicy and skipped U and S. ~I wasn't sure if I should flip the WL/Q values to match the children… but not flipping makes move stat of the child match the node stat of opponent move~ see https://github.com/LeelaChessZero/lc0/pull/1268#issuecomment-624254666:
```
position fen 1K//k1r
go nodes 23
uciloop.cc:222] << info nodes 23 score …
```
> Include verbose stats for the node.

- meson.build
- src/mcts/stoppers/alphazero.cc
- src/mcts/stoppers/alphazero.h
- src/mcts/stoppers/factory.cc
as per #968 but now on the new time manager factory.
startup with param:
`--time-manager=alphazero`
Comment copied over from #968 below: 
Optionally play with alphazero time settings.
After talking with ASilver on Discord, found the explanation that the original alphazero used some different time setting, which is just use 1/20th (thus 5%) of the remaining time available for the upcoming move.
Additionally I just added the wtime (the time increment) for use directly for the upcoming move as well here.
Tests done:
This time setting performs worse than the default lczero time setting. 
- In only 10 games (60sec+1sec) the result was 3 wins for lczero time, 1 for aztime, 6 draws.
- Other 10 games (10sec+0.1sec) the result was even worse:
> Score of lc0.net.42850 vs lc0az.net.42850: 5 - 1 - 4 …
> add alphazero time manager

- src/mcts/node.cc
- src/mcts/node.h
And get rid of `EdgeList` (took 6 bytes extra space than it should have).
NPS drop: -1.6% at random backend.
Memory usage: unchanged! \o/ (was offset by EdgeList refactoring)
Fixes #875.
> Make `wl_` double.

- src/chess/bitboard.h
- src/mcts/search.cc
- src/mcts/search.h
> Move move filter population to a constructor.

- src/engine.cc
- src/mcts/search.cc
r? @borg323 Fix #899 filtering using the new `MakeRootMoveFilter` from #1281
```
Before:
go nodes 2 searchmoves a1a2
Segmentation fault: 11
go nodes 2 searchmoves a1a2 a2a3 a3a4
bestmove a2a3 ponder e7e5
After:
go nodes 2 searchmoves a1a2
error No legal searchmoves.
go nodes 2 searchmoves a1a2 a2a3 a3a4
bestmove a2a3 ponder e7e5
```
> Filter out illegal searchmoves.

- src/mcts/node.cc
This probably is worthy of a fixed node elo test to rule out any strange interactions, but I would estimate positive elo in the 0-1 range ;)
This seems a cheaper alternative to adding more logic to the pick node loop with regard to terminals.
> Clear policy for terminal loss.

- src/mcts/search.cc
Specifically, if a visit proves terminal win status, it should become the best edge even though the n might still be far behind the best.
Also don't recalculate if already the best edge other than in the change to terminal case. Doing this introduces another corner case, but the new logic should handle it. Specifically if a visit proves terminal loss status, it should stop being the best edge even if it has the maximum n.
> Fix bug where pv might not update for best move change.

- src/neural/cuda/layers.cc
- src/neural/cuda/network_cudnn.cc
- 60% memory usage for transformed weights is too optimistic. Try 40% for warning, and 50% for auto-disable of custom_winograd.
- Address @borg323 's comment for my previous pull request (allow user to override with warning).
- also fix (size_t)->(int) conversion warnings in cudnn backend
> fix weight memory check to be more conservative

- src/mcts/node.cc
- src/mcts/search.cc
r? @mooskagh or @Tilps Fix #1291. This regressed with #1280's:
```diff
-  uint16_t GetNumEdges() const { return edges_.size(); }
+  uint8_t GetNumEdges() const { return num_edges_; }
```
```
After #1291:
info string node  (   ) N:       1 (+ 0) (P:  0.00%) (WL:  0.10861) (D: 0.325) (M:  0.0) (Q:  0.10861) (V:  0.1086) 
Term:0 This:0x7fc1bb004230 Parent:0x0 Index:0 Child:0x0 Sibling:0x0 WL:-0.108615 N:1 N_:0 Edges: Bounds:-1,1
After this PR:
info string node  (  20) N:       1 (+ 0) (P:  0.00%) (WL:  0.10861) (D: 0.325) (M:  0.0) (Q:  0.10861) (V:  0.1086) 
Term:0 This:0x7ffc81f27710 Parent:0x0 Index:0 Child:0x0 Sibling:0x0 WL:-0.108615 N:1 N_:0 Edges:20 Bounds:-1,1
```
> Use explicit int for printing verbose and debug num edges.

- src/mcts/search.cc
- src/mcts/search.h
3-4% speedup in random backend. May be noise or hardware dependent, it would be appreciated if more people could test it.
```
./lc0_policy_optimized benchmark --backend=random
===========================
Total time (ms) : 340446
Nodes searched  : 69693334
Nodes/second    : 204711
./lc0_c4c92f6 benchmark --backend=random
===========================
Total time (ms) : 340487
Nodes searched  : 67522311
Nodes/second    : 198310
./lc0_policy_optimized benchmark (t59)
===========================
Total time (ms) : 340808
Nodes searched  : 42638750
Nodes/second    : 125110
./lc0_c4c92f6 benchmark (t59)
===========================
Total time (ms) : 340724
Nodes searched  : 42673511
Nodes/second    : 125243
```
> Small policy calculation optimization

- src/mcts/search.cc
r? @mooskagh This has been slightly annoying me for a while for my scripts that combine multiple verbose outputs as things are just slightly out of line for a forced move:
```
Before:
63494  23.5 f5d3  (833 ) N:       0 (+ 0) (P: 81.74%) (WL:  -.-----) (D: -.---) (M:  -.-) (Q: -0.24998) (U: 1.75504) (S:  1.50506) (V:  -.----) 
63494  24.0 b5c6  (942 ) N:       0 (+ 0) (P: 100.00%) (WL:  -.-----) (D: -.---) (M:  -.-) (Q:  0.58810) (U: 2.14715) (S:  2.73525) (V:  -.----) 
63494  24.5 e8a8  (97  ) N:       0 (+ 0) (P: 15.12%) (WL:  -.-----) (D: -.---) (M:  -.-) (Q: -0.49971) (U: 0.32475) (S: -0.17497) (V:  -.----) 
…
63494  33.5 d7d5  (293 ) N:       0 (+ 0) (P: 54.42%) (WL:  -.-----) (D: -.---) (M:  -.-) (Q:  0.23504) (U: 1.16846) (S:  1.40350) (V:  -.----) 
63494  34.0 a5a4  (903 ) N: …
```
> Show P: 100.0% instead of P: 100.00% to avoid shifting verbose output.

- meson.build
This enables usage of system eigen library if it is present. Before it was not possible to build without pulling subproject.
Should I [force subproject for windows](https://github.com/LeelaChessZero/lc0/blob/master/meson.build#L471)?
> Check if eigen is availiable before pulling subproject

- src/mcts/node.cc
- src/mcts/node.h
- src/mcts/search.cc
- src/mcts/search.h
Adjust parent node Q/D/M values to act as if newly converted terminals always had the Q/D/M values that they now have.
This will 'momentarily' be confusing for search - so may need to be combined with something like crem's recent time management adjustment that waits for best N to catch up with best Q to avoid missing out on taking advantage of the information gain applied.
I've only done minimal validation that the values move the direction I expect them to when terminal status gets determined.
Given this is in the return loop it probably will need nps or check at time control in addition to any proof of improvement at fixed nodes.
But first I'll try to demonstrate at fixed nodes if I can find a spare minute or two on my machine :P
> Terminal correction

- src/mcts/search.cc
r?@AlexisOlson or @Tilps  Following up from #1230. I do see `child_m - parent_m` is redundant if the child is not visited…
> Calculate verbose M effect with delta-M like PickNode.

- src/neural/network_demux.cc
Allows to do `--backend=demux --backend-opts=backend=blas,threads=32` to split batches over 32 blas threads. This can be taken to the next level with something like `--backend=multiplexing --backend-opts=opencl, demux(backend=blas,threads=32)`.
> demux over all (blas) threads

- src/utils/filesystem.h
- src/utils/filesystem.posix.cc
- src/utils/filesystem.win32.cc
Fixed the issue #831
Fixed by returning 0 instead of throwing the exception. Two involved functions are GetFileSize and GetFileTime. All code which called those functions can work well with returns of zero.
> Fixed issue 'Cannot stat file'

- src/neural/factory.h
- src/selfplay/game.cc
- src/selfplay/game.h
- src/selfplay/tournament.cc
- src/selfplay/tournament.h
- src/utils/optionsdict.cc
- src/utils/optionsdict.h
- src/utils/optionsparser.cc
It's a bit too unwieldy and ugly, but it's the best I could come up with.
So, before:
```
Root_params
|
+ player1
|
+ player2
```
After:
```
Root_params
|
+ player1
|       |
|       + white
|       |
|       + black
|       
+ player2
|       |
|       + white
|       |
|       + black
|
+ white
|
+ black
```
`root_params.white` and `root_params.black` are "aliases" (maybe a poor term) for `root_params.player*.white` (and `root_params.player*.black`).
When you e.g. access the parameter `player1.black.backend`, it's looked up in the following order:
1. `(default.root.)player1.black.backend` (self)
2. `(default.root.)black.backend` (alias) Note that parents of the alias are not looked up.
3. `(default.root.)player1.backend` (parent of the self)
4. `(default.root.)backend` (parent of parent …
> Per color settings.

- src/mcts/node.h
- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/selfplay/tournament.cc
- src/utils/fastmath.h
Profiling on windows with LTO enabled, I noticed that edge.GetQ was not being inlined in our hottest loop. If I removed the nested logit_q path it was inlined and there was a dramatic performance increase in CPU limited scenarios. (Combined with one other small change it was ~15% increase in nps over a 5 million node search).
Given that logit-q has failed to prove itself in practice, having the potential for this much CPU bottleneck when the feature is disabled doesn't seem a worthwhile situation.
Until such time as there seems a new reason for it - it seems prudent to remove it entirely.
> Remove logit q.

- src/mcts/search.cc
When combined with removing logit_q to ensure that LTO inlines GetQ - this gives a total of 15% performance improvement in a  CPU bottlenecked scenario involving MLH that I took from Sufi18 on my windows machine.
The quadratic factor in abs(Q) is the next most expensive part of the MLH computations, but its small compared to having to call a library function here.
> Performance improvement for windows compiles with mlh.

- src/neural/blas/network_blas.cc
- src/neural/cuda/network_cudnn.cc
- src/neural/dx/network_dx.cc
- src/neural/opencl/network_opencl.cc
For anyone who wants to get back the small MLH overhead, adding `--backend-opts-mlh=false` skips the mlh calculations in the backend.
> backend option to disable mlh

- src/mcts/node.cc
- src/mcts/node.h
- src/mcts/search.cc
This has 'obvious' improvements in cpu profiling - and small but measurable improvements (2-3%) with a 8 million node search of startpos T70 running on 2080TI on a fast intel cpu using windows PGO build.  8 million node search appears more gpu bound than cpu bound for most of the time.
FetchSingleNodeResult is definitely slower (maybe 30%), but the gains in PickNode are much better and clearly offset it in the profile traces I've gathered.  Maybe the sort could be optimized a bit more for small arrays - but it already seems a win.
NOTE:
This is not purely an nps gain. By changing the sort order of the edges it changes the order of tiebreaks in the pick inner loop.
I think the new mode is 'logically' better - but I'll try to run a before/after elo test just in case.
For reference - tie …
> Sort edges to reduce cpu load by allowing an early out in the inner pick loop.

- appveyor.yml
- src/mcts/params.cc
4 seems a good value for openblas and dnnl, while for android 7 looked better in some tests.
> adjust minibatch-size for appveyor cpu builds

- appveyor.yml
Unfortunately, meson 0.55 (released a few hours ago) breaks the build, so stay with the last known working version.
> fix meson on appveyor to 0.54.3

- README.md
Went through some rather frustrating troubleshooting... turns out that Xcode Developer tools now contains these SDK headers.
> Editing installation instructions for Mac for Different OSes

- src/chess/position.cc
- src/chess/position.h
- src/mcts/node.cc
- src/mcts/node.h
- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/mcts/search.h
- src/selfplay/tournament.cc
EDIT: It is fully functional now, tests are welcome! Also, the tree reuse problem with level 1 being complicated has been solved successfully, so the heuristic of level 2 probably isn't needed anymore.
Original post:
This is a draft for a twofold draw scoring patch. For development + testing purposes, this PR introduces an `int TwoFoldDrawLevel = 0...3` where the levels are:
- `0`: never score twofold repetions as draws. This is current behavior.
- `1`: score twofold repetitions when their first repetition is at root or in the tree, but not when it happened in history. This is the theoretically sound implementation, avoiding delusional evals, making this the preferred implementation.
- `2`: score twofold repetions as draws when they happen at depth 4 or deeper in the tree. This is …
> Twofold repetition draw scoring

- src/selfplay/game.cc
- src/selfplay/game.h
- src/selfplay/tournament.cc
- src/selfplay/tournament.h
as per #905 now on the c17 version of the code.
Add syzygy tablebases to use these for selfplay games.
The goal is to save time in training and game matches: for example when contributing to leela-training and matches I've seen games prolong between KRvsKR for 200+ moves, just wasting CPU/GPU cycles.
So the goal here is to use tablebases when those exists for clients; it should just use the tablebases available on your system even if that's only 4 or 5 pieces instead of 6 or 7 piece TB.
Seems to work when starting lc0 as follows:
lc0 selfplay --visits=800 --syzygy-paths=c:\path_to\tablebases
After this is merged, this also needs the go-client to pass on the syzygy-path from commandline to lc0 so that local installed client tablebases are indeed being used, or the TB might be configured in …
> Syzygy tablebase for use with selfplay

- meson.build
- src/neural/cuda/common_kernels.cu
- src/neural/cuda/fp16_kernels.cu
- src/neural/cuda/kernels.h
- src/neural/cuda/layers.cc
- src/neural/cuda/layers.h
- src/neural/cuda/network_cudnn.cc
- src/neural/cuda/winograd_helper.inc
A relatively small/easy optimization to speed the custom winograd convolution path further.
In the original implementation of custom winograd path, we had three passes for each convolution:
1. input transform.
2. GEMM
3. output transform (fused with RELU, bias addition, and optionally SE operation)
Because the residual tower is made up of many such convolutions one after other, we can fuse the output transform of the first convolution with the input transform of the next convolution - doing them in the same kernel. So, after this optimization we have each convolution do:
<input is already in winograd transformed space>
1. GEMM
2. Output Transform, followed by SE/relu/bias, followed by Input transform (for next convolution)
For the second convolution in each block, we also need to store …
> Residual block fusion winograd optimization

- src/neural/cuda/network_cudnn.cc
- src/neural/cuda/winograd_helper.inc
Removes `__launch_bounds__(384)`
Disables optimization for fp32 but allows override from options
> res block fusing changes

- src/neural/cuda/network_cudnn.cc
Some cudnn backend crashes were reported because `use_res_block_winograd_fuse_opt_` is used uninitialized when `custom_winograd` is false (the default for small nets and RTX20x0 cards).
> fix unitialized variable

- meson.build
Generating code for all fp16 supporting cuda architectures resulted in unnecessarily large executables. We can restrict this to CC > 7.0 for windows (as it was so far), add CC = 6.0 on linux and only include the Jetson architectures for arm linux.
> restrict cuda architectures built

- src/benchmark/backendbench.cc
Current logic is to replace batchsize with highest nps, if new nps is 1+threshold times higher than previous best.
However, it is known that generally higher batchsize numbers perform worse in gameplay, e.g. a 4x higher batchsize with 1.05x higher nps shouldn't be accepted while a 1.10x higher batchsize with 1.04x higher nps is most probably better.
Now the acceptance rule is based on a linear function requiring +10% nps (compared to previous best) for each +100% of batchsize (to previous best).
Example:
```
batchsize ratio    nps ratio 
1.5                  1.05
2.0                  1.10
3.0                  1.20
```
Edit: Based on some short test matches I suspect that the default threshold can be increased from 0.1 to 0.2 (+15% nps with 2x batchsize was weaker in a test):
```
batchsize …
```
> Improvement of backendbench assistant.

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/mcts/search.h
- src/selfplay/game.cc
- src/utils/logging.cc
1) GetBestChildrenNoTemperature was not respecting the GetN test before accessing a node's details.
2) PopulateCommonIterationStats had similar issues.
3) GetTwoFoldDraws property was used by SearchWorkers without being cached.
4) Wrap std::localtime usage in a mutex.
5) Fix a pointless access of node WL/D/M for collisions.
6) Put nps_start_time_ behind counters mutex to avoid races.
7) Ensure search is disposed before performing the move during selfplay.
> Fix multiple tsan reported issues.

- src/mcts/search.cc
- src/mcts/search.h
I could make this an option, but I don't think the added complexity is worth it.  Yes we might not report mate score quite as frequently, but given our mate scores involving TB hits generally cause more confusion than not, and more realistic play is highly likely to occur with WDL disabled in search - the good should outweigh that tiny little detail.
Stockfish does this unconditionally as well - (further more disables WDL lookups if root position is a WDL loss or draw (even if DTZ is missing)- I guess to try and get some swindling in? - I don't think we can be bothered with that subtle detail).
> Disable WDL lookups when playing from DTZ restricted search position.

- src/mcts/params.cc
Assuming #1470 and #1471 are committed, I think its worth turning this off by default for a release.
If we don't get complaints, maybe we can even remove the setting later on.
> Turn syzygy fast play off by default.

- src/mcts/search.cc
Rather than duplicating code.
Cleanup post PR1490 merge.
> Change PickNodeToExtend to use EnsureNodeTwoFoldCorrectForDepth

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/mcts/search.h
Inspired by investigations into `position fen 1r1qr1k1/6bp/1n4p1/2pPpp2/1n3P2/1QN5/1P1N2PP/R4RBK w - - 0 24`
In that position on my machine this change almost doubles NPS at one point during the search (a few million nodes in).
In my 'standard benchmark run' it may be worth a couple of percent.
I think this heuristic can probably be improved upon, but it seems a pretty good start.
Since its an early exit - so long as the nps stays high I think its a clear win (the early exit itself is potentially worth elo at fixed nodes - untested).
I am unclear if there are any scenarios where this will be a net loss of nps - but I haven't thought of any of signifiance so far.
> Early exit if backend is idle and there is work to do.

- src/mcts/search.cc
Should reduce picking latency.
NPS tests not started yet - but fixed node test underway is 'fine' so far.
> Actively split pick tasks as early as possible.

- src/neural/cache.h
- src/utils/cache.h
Has less pointer chasing than the previous version.
This comes from PR1483.
On my machine I've gotten mixed results.
Simple 34 position 10 second a move benchmark (with appropriate command line args) was almost 2% faster.  But go nodes start position with two different cache sizes were both slightly slower. 
I think it should do better on 'tcec like machines' but I haven't benched there yet.
> HashKeyedCache

- src/mcts/params.cc
- src/mcts/search.cc
Both zz and I have found a speed up in benchmarking reducing this parameter to its minimum value.
Also clean up some comments that were wrong/obsolete that were bothering me.
> Better default value for minimum picking work and clean up some old comments

- build.cmd
In some systems gcc is detected when building on windows, which we don't currently support. This should make it easier to diagnose.
> bypass meson compiler detection in build.cmd

- src/utils/fastmath.h
@Tilps noticed that MSVC is not optimizing away the calls to `floor()` and after further investigation it seems that only gcc does.  This code replaces `floor(a)` with `static_cast<int32_t>(a)` for positive a and `static_cast<int32_t>(a - 1)` for negative a. While this is obviously wrong for negative integer a, the approximation used has zero error in this case (by design). 
Microbenchmarks with gcc show the resulting code to be considerably faster than the original, that already had the call to `floor()` optimized away.
> replace floor in FastPow2 and rename to FastExp2

- src/mcts/node.cc
#1515 broke playing from book as reported in #1517,  #1518 fixed playing from book, but left certain analysis type actions still broken.
This removes the 'legal' move check and just fixes the solid tree related code that #1515 was trying to fix the crash for, thus properly fixing #1517.
> Fix crash instead of trying to validate legal moves.

- src/neural/cuda/layers.cc
- src/neural/cuda/layers.h
- src/neural/cuda/network_cudnn.cc
This is a follow-up to #1422. Needs performance testing whether it brings a small nps improvement.
1. The softmax of WDL values is probably not very well suited to a gpu implementation. 
2. @ankan-ban suggested doing the softmax after freeing the lock.
> replace cudnn softmax with cpu version

- .gitignore
- src/mcts/stoppers/smooth.cc
(which makes all remaining moves instamoves)
Fixes #1454
> Don't divide by zero after the instamove.

- src/benchmark/backendbench.cc
Updating Clippy threshold to a parameter value that favors higher batch sizes (closer in functionality to old algorithm).
Snapshot of a running test before release deadline: mb32 is batch size 32 (1st peak), mb68 is 2nd peak:
```
1 lc0.net.256x20-t40-1541_mb68    :     4.3   11.1    69.6    1462      61.0
2 lc0.net.256x20-t40-1541_mb32    :     0.2   10.9    51.7    1463      61.9
3 stockfish-dev                   :     0.0   ----     ---    2925      61.5
```
Although MB=68 is the one with 21% higher NPS in backendbench and 32% higher NPS in match logfile, the result is very close but indicating that current threshold prefers smaller batch sizes too much (batch size 32 would be picked as best).
Lines in graph show when the current best NPS is replaced by the clippy backendbench.
General …
> Clippy Threshold update.

- src/mcts/params.cc
This value we use at competition. It has clear nps improvement properties.
Fixed node 1k test non-regression:
Score of lc0 more-ooo vs lc0: 354 - 336 - 1310 [0.504]
...      lc0 more-ooo playing White: 231 - 131 - 638  [0.550] 1000
...      lc0 more-ooo playing Black: 123 - 205 - 672  [0.459] 1000
...      White vs Black: 436 - 254 - 1310  [0.545] 2000
Elo difference: 3.1 +/- 8.9, LOS: 75.3 %, DrawRatio: 65.5 %
2000 of 2000 games finished.
> Increase default moooef

- src/mcts/search.cc
I didn't merge the original PR including this change before doing the multigather branches. Multigather branches introduced a new version of this function in parallel.  Then following cleanup brought everything to use the new version, meaning the old version with the correct code had been lost.
> Return lost check for whether root node is DTZ before doing WDL lookups in search.

- src/mcts/params.cc
- src/selfplay/tournament.cc
Testing in training looks 'fine' - so I think its time to make it the default.
Forcing the task workers default to 0 for selfplay since we already have parallelism to chew up cpus.
> Make multi-gather default.

- src/mcts/search.cc
Fixes "Stopped search: Reached visits limit" log file spam when the visits limit is reached in analysis mode.
In infinite analysis mode, once stop_ is true but "stop" hasn't yet been received from the GUI, there is no need to spam FireStopInternal() (since the watchdog thread wait_for is non-blocking at that point anyway), and none of the ShouldStop methods for stoppers that can be present at such times appear to have important side effects. This fix should therefore be safe.
Fixes #1507
> Fix log spam during infinite analysis

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
Similar 1k nodes regression to limiting n_in_flight - after partial tuning I got the following result.
Score of lc0 vs lc0 dev: 438 - 303 - 1259 [0.534]
...      lc0 playing White: 273 - 103 - 624  [0.585] 1000
...      lc0 playing Black: 165 - 200 - 635  [0.482] 1000
...      White vs Black: 473 - 268 - 1259  [0.551] 2000
Elo difference: 23.5 +/- 9.2, LOS: 100.0 %, DrawRatio: 62.9 %
2000 of 2000 games finished.
Bonus here is that max collision visits preferred curvature is closer to straight line which potentially implies we can scale MCV=tree_size/4 to an almost arbitrary level.  Since this increases the limit over 1000 for even moderately sized trees - this potentially has better nps characteristics than our competition version. Also since this is a collision limit and not an …
> Limited mcv

- meson.build
- meson_options.txt
For windows, mimalloc seems to be a good replacement for the default allocator. Huge trees are destructed many times faster and I also see a measurable nps increase with the random backend.
To build you need to pass `-Dmalloc=mimalloc -Dmimalloc_libdir=c:\path\to\mimalloc\libraries` to meson, and to run you will need to copy `mimalloc-redirect.dll` and `mimalloc-override.dll`.
Thanks to @cn4750 for the suggestion.
> support for windows mimalloc

- src/benchmark/backendbench.cc
Adds two new options, `--start-batch-size` and `--batch-step` and runs one minimal computation outside the loop to warm-up the backend.
> Improvements for backendbench

- src/neural/cuda/common_kernels.cu
- src/neural/cuda/fp16_kernels.cu
- src/neural/cuda/kernels.h
- src/neural/cuda/layers.cc
- src/neural/cuda/layers.h
- src/neural/cuda/network_cuda.cc
- src/neural/cuda/network_cudnn.cc
- src/neural/cuda/winograd_helper.inc
- Allows better memory access pattern.
- As the optimization is currently limited to networks with filter size <= 384, add __launch_bounds__ compiler hint to allow it use max possible no of registers to support upto 384 channels.
- Get rid of residual block path from cudnn backend (people who are able to use that with cudnn backend should be already running the new cuda backend).
With lc0 benchmark running on A100, recent T60 network, minibatch-size=96:
Baseline: 54152
Optimized: 55320
> Use NHCW layout for fused winograd residual block

- src/neural/cuda/common_kernels.cu
- src/neural/cuda/fp16_kernels.cu
- src/neural/cuda/inputs_outputs.h
- src/neural/cuda/kernels.h
- src/neural/cuda/layers.cc
- src/neural/cuda/layers.h
- src/neural/cuda/network_cuda.cc
- src/neural/cuda/network_cudnn.cc
- src/neural/cuda/winograd_helper.inc
- Create cuda stream and memory needed to run the network for each InputsOutputs object.
- This allows concurrent execution of multiple parallel Eval requests. 
- Note that this PR also include kernel opts from PR #1567 
Some performance nos (for lc0 benchmark running on A100, recent T60 network, minibatch-size=96 all other params default)
```
Baseline       : 54152
Kernel opts    : 57154
+ multi-stream : 67439
+ roundrobin   : 67249 
+ t 3 ( w/ RR) : 70419
t 4 ( w/ RR) : 72333
t 4 ( w/Mux) : 73442
```
> Multi-stream Optimization for CUDA backend

- appveyor.yml
- scripts/appveyor_win_build.cmd
- scripts/appveyor_win_package.cmd
Builds and links with mimalloc-1.7.1 and adds the appropriate dlls, license and readme to the release zip.
This should be committed right before a release, otherwise the appveyor artifacts will be unusable.
> add mimalloc to release builds

- src/neural/cuda/network_cudnn.cc
recent changes in PR1567 seems to cause GTX16x0 to crash when using custom_winograd
may need to add extra code to throw exception when set to true
> change default winograd on gtx16x0

- src/neural/cuda/network_cuda.cc
We need some heuristic for when to turn it on, some cards can't handle it. So make it default off for now,
> set cuda multi_stream off by default

- src/chess/position.cc
- src/mcts/stoppers/smooth.cc
Fixes #1585.
There are surely more to fix, including some simple and obvious things, but in this PR I'd really like only to fix the most urgent issue of instamoving due to nps misprediction.
What it PR does:
1. If at any moment, the current avg move nps (move nodes / move time, the thing that is displayed in `uci`) is higher than predicted, just assign that nps to whatever time manager uses.
2. If we are longer than `nps-update-period` (default is 20 seconds) in the move, also use "displayed move nps" as time manager nps.
3. Otherwise linearly decrease nps at the rate so that `nps-update-period` after the move start it lands exactly at current move's nps.
The graph of nps estimation for 14 seconds nps-update-period:
> Quickfix for smooth TM nps misprediction.

- README.md
Forgotten during the 0.28 release.
> Update 0.27 to 0.28

- src/neural/encoder.cc
The current comment has two versions of "white can castle kingside".
It seems that "black" is "they", and therefore the latter instance should say black.
---
Possible I should modify the comments to say "us" and "them" instead of "black" and "white" while I'm at it?
> Fix typo in comment about net input format

- src/neural/cuda/cuda_common.h
- src/neural/cuda/inputs_outputs.h
- src/neural/cuda/network_cuda.cc
- src/neural/cuda/network_cudnn.cc
- set CUBLAS_PEDANTIC_MATH to avoid cublas making use of tensor math on TU11x GPUs.
- From documentation:
"Starting with cuBLAS version 11.0.0, the library will automatically make use of Tensor Core capabilities wherever possible, unless they are explicitly disabled by selecting pedantic compute modes in cuBLAS (see cublasSetMathMode(), cublasMath_t)."
- Unfortunately there is a bug in cublas which enables tensor math even on TU11x GPUs which is emulated in software is orders of magnitude slower, so this PR is a workaround to disable tensor math to make cublas pick 2xFP16 math kernels on TU11x.
> WAR for cublas issue on TU11x GPUs with version CUDA 11.0+

- src/neural/cuda/common_kernels.cu
- src/neural/cuda/fp16_kernels.cu
- src/neural/cuda/kernels.h
- src/neural/cuda/layers.cc
- src/neural/cuda/layers.h
- src/neural/cuda/network_cuda.cc
1. Do keys, queries, values matrix multiplications in parallel in the encoder layers (as batched GEMM).
2. Do keys, queries matrix multiplication for policy head in parallel.
3. Add kernel to do batched bias addition. Optimize it to reach close to full memory bandwidth utilization (AddVectors kernel was not written with performance in mind).
4. Optimize LayerNorm and Softmax kernels to reach close to full memory bandwidth utilization.
About 7% improvement in total end to end network evaluation time on RTX 3080 for the 20b Attention head network I got from Arcturai (20b_43-swa-2000000.pb.gz):
Before: Benchmark batch size 256 with inference average time 9.68394ms - throughput 26435.5 nps.
After: Benchmark batch size 256 with inference average time 9.07259ms - throughput 28216.8 nps.
> Optimizations for attention policy head

- meson.build
- src/neural/blas/fully_connected_layer.cc
- src/neural/blas/network_blas.cc
- src/neural/shared/activation.cc
- src/neural/shared/activation.h
- src/neural/shared/activation.ispc
This brings evaluation speed for T79 very close to T75 when compiled with ispc, compared to almost half without.
> ispc mish version for better vectorization

- src/mcts/search.cc
This allows for temperature to perform random move making by policy instead of visits when node limit is 1.
It is recommended that PST is set to 1 if you wish to randomize by the unmodified policy output.
> Temperature chooses by P instead of N when only 1 node

- src/neural/blas/network_blas.cc
- src/neural/blas/se_unit.cc
- src/neural/blas/se_unit.h
- src/neural/blas/winograd_transform.ispc
Big update: Using SGEMM instead of hardcoded multiplication is a big gain for attention policy, >6% for T79.
~~This~~The rest is worth about 3% for 10b nets, less for larger ones. There are two parts:
1. Optimization of the ispc Winograd transform code.
2. Fusion of the bias addition with the SE unit, where it can be done at the channel level. (So each channel bias is added twice, once in the global pooling and once together with the SE bias addition (but scaled), so 2 additions and 1 multiplication per channel instead of 64 additions and the corresponding memory accesses.
> Speed optimizations for the blas backend.

- appveyor.yml
- scripts/appveyor_win_build.cmd
- scripts/appveyor_win_package.cmd
- src/neural/onednn/layers.cc
- src/neural/onednn/layers.h
- src/neural/onednn/network_onednn.cc
This is not yet fully optimized, but works well enough. 
Note that it needs a new `dnnl.dll` to work, and the latest one is uploaded on appveyor, compiled with cpu and gpu support. To use the igpu you add `--backend-opts=gpu=0` to the command line. Similarly, the latest `dnnl.dll` versions seem to have trouble selecting Winograd convolution automatically, so `--backend-opts=winograd=true` is worth trying on a cpu.
Also for nets larger than T74 it seems a single search thread is better than two, at least on my test system.
> onednn backend support for mish and attention policy

- src/neural/onednn/layers.cc
- src/neural/onednn/network_onednn.cc
The new dnnl.dll (that we need for mish) on its own chooses Winograd convolution on the igpu and not on the cpu (probably confused by the 8x8 planes). Tests show that for us Winograd convolution on the igpu is form slightly to a lot worse, but a big gain on the cpus where it is available.
During those tests it was also noticed that mish fused with convolutions always has a big performance overhead on the gpu, so now it is a separate primitive unconditionally.
> onednn winograd selection heuristic

- src/utils/weights_adapter.h
Switch from deprecated std::iterator to using new way of defining iterator traits.
> Fix warnings.

- src/neural/network_check.cc
Removing 🧹 the const variable that generates the following compiler warning:
```
../../src/neural/network_check.cc:117:24: warning: unused variable 'kNumOutputPolicies' [-Wunused-const-variable]
static constexpr int kNumOutputPolicies = 1858;
^
1 warning generated.
```
> Warning cleanup 🧹

- src/neural/dx/MetaCommand.h
- src/neural/dx/layers_dx.cc
- src/utils/fp16_utils.h
Silences compiler warnings triggered by semicolons after namespace-closing curly brackets and fixes formatting of affected files (`layers_dx.cc`).
> Namespace semicolons

- src/neural/dx/layers_dx.cc
The same header file was included twice in this file.
> remove double header

- meson.build
I just went through the [walkthrough for building the Python-bindings](https://github.com/LeelaChessZero/lc0/pull/1261), and found that my versions of Python above 3.10 are mistaken for being older than 3.7. Using `.version_compare()` instead of direct string comparison fixes this.
I'm guessing that this is pretty niche, but I was able to complete the build process (at least for the bindings) with meson using 3.10.
> Version detection in meson.build for new editions of Python

- src/mcts/search.cc
This should allow smart pruning to work with low nps limits.
> inform time manager of any nps limit

- src/neural/cuda/network_cudnn.cc
Just a straight port of the cuda code. At a minimum, some refactoring is required (`getMaxAttentionHeadSize()`).
~~Completely untested~~ ~~Very lightly tested.~~ ~~T78 doesn't work but T80 *seems* fine, which hints at insufficient scratch memory allocation.~~ The issue seems to have been the tensor memory size allocated, not the scratch size.
> cudnn attention policy

- src/mcts/params.h
Small typo in the explanation of private parameters.
> fixed typo in comment

- appveyor.yml
- dist/README-onnx-dml.txt
- dist/README-onnx.txt
- scripts/appveyor_win_build.cmd
- scripts/appveyor_win_package.cmd
- src/neural/onnx/network_onnx.cc
This was repurposed to build onnx-dml. Note that onnx-dml is now the higher priority onnx backend, but it is only built if the required header is found, which is only available if a directml enabled onnxruntime is used.
> build onnx-dml package

- src/mcts/stoppers/smooth.cc
- src/mcts/stoppers/stoppers.cc
Should help against this:
Not tested, likely also fixes #1582.
> In smooth TM, use piggybank when it seems like the bestmove can be overtaken.

- src/main.cc
- src/mcts/node.cc
- src/mcts/search.cc
- src/mcts/search.h
- src/neural/blas/network_blas.cc
- src/neural/network.h
- src/neural/network_demux.cc
- src/neural/network_mux.cc
- src/utils/numa.cc
Apparently binding threads to a windows processor group is a bad idea if lc0 is used simultaneously with SF for analysis: both engines try to use the same cores.
Since thread binding is only useful for more than 32 threads, in most cases it may be better to let windows handle the allocation.
The only real use case is with the blas backend, so here thread binding is made conditional on `USE_BLAS`. This does not include the eigen backend, but I think this is acceptable as it is mainly intended as a reference implementation.
> only use thread binding with blas backend

- src/neural/cuda/layers.cc
- src/neural/cuda/network_cuda.cc
- goal is to fit activations of residual block in L2 cache.
- around 6.7% improvement in T80 networks.
- Expected to only help Ada GPUs with larger L2 cache capacities.
With 807647 network on RTX 4090 - 
Before:
```
Benchmark batch size 32 with inference average time 1.58066ms - throughput 20244.6 nps.
Benchmark batch size 64 with inference average time 2.01741ms - throughput 31723.8 nps.
Benchmark batch size 96 with inference average time 2.32485ms - throughput 41293 nps.
Benchmark batch size 128 with inference average time 2.94163ms - throughput 43513.3 nps.
Benchmark batch size 160 with inference average time 3.54371ms - throughput 45150.4 nps.
Benchmark batch size 192 with inference average time 4.34863ms - throughput 44151.8 nps.
Benchmark batch size 224 with inference average time …
```
> Persistent L2 cache opt for cuda backend

- src/neural/metal/mps/NetworkGraph.mm
Versions of macos prior to 12.3 do not have `[MPSGraph splitTensor]`. This PR changes attn policy promo computation to use `sliceTensor` to support older macos 12.x versions.
> Use sliceTensor instead of splitTensor for attn policy promo

- src/neural/encoder.cc
If a position is given by FEN that includes en passant info, we know what the previous move was, so we get one extra history move. This is now used even when no history filling is done.
> allways fill history for en passant

- src/engine.cc
If you change the syzygy path to something invalid in order to disable tb use and later back to the original path to use the tb again it doesn't work.
> fix syzygy loading

- src/neural/onnx/builder.cc
- src/neural/onnx/builder.h
- src/neural/onnx/converter.cc
- src/neural/onnx/converter.h
- src/neural/onnx/network_onnx.cc
This is the onnx equivalent of the fast mish we already use, only in fp32 mode (fp16 breaks badly) and on by default for onnx-cpu where it is considerably faster.
> optional alternative mish implementation

- src/neural/onnx/network_onnx.cc
The onnxruntime thread usage is not playing well with our search threads, at least with onnx-cpu. Restricting each evaluation to a single thread seems to be a decent performance win for more that 2 search threads with onnxruntime 1.4.0, that uses threads more aggressively. Here I introduce a `threads` backend option that defaults to 1 for onnx-cpu and 0 (default) otherwise.
> option for onnx threads

- appveyor.yml
- meson.build
- meson_options.txt
Apparently there are systems with RTX gpus and older processors without native fp16 conversion instructions, so I made the cuda/cudnn builds to default to the fallback conversion code.
> separate build system control for f16c instructions

- src/utils/numa.cc
Apparently I was using `GetLogicalProcessorInformationEx()` wrong, the `ReturnedLength` must be zero to get the correct structure size and not just the `Buffer` pointer. We got lucky with this when `Numa::Init()` was called from `main()` but now that it is in the blas backend it sometimes fails.
> fix numa bug

- build.sh
- meson.build
This fixes a build failure encountered on an Ubuntu Github cloud runner, where the meson logs contained the line `!meson_ci!/ci_include "/tmp/tmp.57HLIN4Fd8/lc0/build/release/build.ninja` that followed `Found ninja-1.11.1.git.kitware.jobserver-1 at /home/runner/work/lczero-onnx/lczero-onnx/build/venv/bin/ninja`. Here is a snippet of the log:
```
Found ninja-1.11.1.git.kitware.jobserver-1 at /home/runner/work/lczero-onnx/lczero-onnx/build/venv/bin/ninja
detecting CPU family based on trial='x86_64'
detecting CPU family based on trial='x86_64'
detecting CPU family based on trial='x86_64'
detecting CPU family based on trial='x86_64'
detecting CPU family based on trial='x86_64'
detecting CPU family based on trial='x86_64'
detecting CPU family based on trial='x86_64'
detecting CPU family based …
```
> Fix ninja detection on some platforms.

- scripts/compile_proto.py
- src/neural/decoder.cc
- src/neural/network.h
- src/trainingdata/reader.cc
- src/utils/protomessage.cc
- src/utils/protomessage.h
This is a part of the `uci info` refactoring in my https://github.com/mooskagh/lc0/tree/json branch.
Changes:
* Added support of dumping a proto as JSON.
* Forward (and circular) references are now possible
To allow forward references, all nested messages and enum are now in global scope, and parent classes have `using` directives, just like in Google protobuf compiled files.
> Refactor probuf compilation

- src/neural/onnx/network_onnx.cc
Changed the default steps to 4 from 8, limiting the number of onnxruntime sessions with different batch size (used to get decent performance from directml). This has a performance impact for smaller nets, but seems to solve out of memory issues with some gpus.
> change onnx-dml default steps

- scripts/appveyor_win_package.cmd
Contributing with any other backend doesn't really make sense. Also uses a download link directly from github, so we can avoid the error prone one from appveyor.
> Package the client only with cuda

- src/utils/filesystem.h
- src/version.h
It seems that some standard header file, most likely string, used to include cstdint, so it was omitted in some places. Fixes #1882.
> fix incllude files

- src/mcts/stoppers/legacy.cc
adds a first-move-bonus to legacy time manager to accompany book-ply-bonus for shallow openings especially in FRC and DFRC.
Reasoning: Due to high % of tree reuse and saved time from smart pruning, LTC games at TCEC without spending more time on the first move have nearly linearly increasing node counts for the first 8-12 moves (see #1493). When playing chess from regular startpos, this isn't an issue due to policy head agreeing with value head. However, we can't rely on policy in FRC and DFRC, so having an option which does the same without book exits would be required. Based on the 8-12 move observation which is (nearly) made equal for 12+ ply exits with `book-ply-bonus=0.4`, I recommend using `first-move-bonus=5.0`.
> Modify legacy TM to allow a bonus for first move if we expect shallow openings

- src/mcts/params.cc
Apparently cutechess tries to set `contempt` to the default empty string, which breaks the `IsDefault()` check.
> fix empty contempt handling

- src/mcts/stoppers/simple.cc
Wasnt happy with some of the calculations and variable names so I made some changes and ran new tests. I believe this version to be simpler, more intuitive, and better performing. Of course there is the possibility that it will need a different tune with more current nets.
Full test details in discord (https://discord.com/channels/425419482568196106/530486338236055583/1100426590824968243)
**SF Time control:** 1.66s+0.0277s
**LC0 Time control:** 10s+0.166s
```
1 sf            :     0.0   ----  1657.5    3000    55     100  800  1715  485    57
2 lc0-simple    :   -27.8   11.8   691.0    1500    46      99  255   872  373    58
3 lc0-legacy    :   -46.6   11.2   651.5    1500    43     ---  230   843  427    56
```
**SF Time control:** 2s+0s
**LC0 Time control:** 10s+0s
```
1 sf …
```
> Revised 'simple' TM

- meson.build
Newer versions of nvcc have a `-arch=all-major` option that compiles code for all `sm_?0` architectures. Since we still need to support earlier nvcc versions, this PR does the same in a roundabout way for fp16 code, and should considerably speed up compilation.
> simplify cuda architectures used

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
This renames the `ContemptPerspective` uci option to `ContemptMode` (and the command line option) with new option names:
* `play`
* `white_side_analysis`
* `black_side_analysis`
* `disable`
In contrast to the current version, `disable` only forces `Contempt` to zero, to keep `WDL_mu` score type and WDL sharpening working.
> rename contempt perspective to contempt mode

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
Originally, the drawscore implementation #1066 was intended for both contempt/humbleness and Armageddon support. Since then it turned out however that
1. the parametrization doesn't even span all possible combinations
2. the effect on opening selection etc is very miniscule
3. we were using symmetric settings between white and black anyway
As we have a working contempt implementation now with #1791, we can reduce drawscore to the one remaining use case, where Armageddon is one extreme case, and we only need 1 parameter for that instead of 4.
> Drawscore simplification for Armageddon

- src/benchmark/benchmark.cc
- src/engine.cc
- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/mcts/search.h
- src/selfplay/game.cc
Makes sure play contempt mode is never used inside the search, it is switched to white/black depending on the first move side, same in normal searches, flipped when pondering or disabled in infinite search. For infinite search there is a warning if contempt would have an effect.
In addition there is a fix for a preexisting wdl display bug, w and l were swapped while pondering.
Also some cleanups.
> handle play contempt mode with infinite search

- src/mcts/params.cc
- src/mcts/search.cc
Changed default values for v0.30 release:
- mlh-threshold to 0.8 as we now have a continuous behaviour. Training runs explicitly set threshold to 0, so no issues there.
- centipawn fallback for WDL_mu to only kick in if W or L < 0.2%, which should happen virtually never. Will still behave jumpy if around that threshold and needs a proper fix at some point, but eval at this point doesn't matter anyway anymore, 
- default scoretype to WDL_mu. Thanks to #1898, `WDL_mu` now is always calculated properly (even if contempt is disabled), and we use it everywhere anyway.
> change default values for v0.30 release

- meson.build
This fixes the error reported in https://github.com/LeelaChessZero/lc0/pull/1905#issuecomment-1656985747
The error is `meson.build:507:26: ERROR: The == operator of str does not accept objects of type list ([])`, this was not triggering in older meson versions.
> fix build error with newer cuda versions

- .circleci/config.yml
Apparently getting ispc through homebrew stopped working for the macos image we use, so we get it directly from github. As a bonus, this is also several minutes faster, as we skip the slow homebrew update.
> fix circleci macos build

- src/neural/onnx/converter.cc
While doing some onnx tests, I noticed attention body nets were not working with `opset=7` as the `Expand` operand was introduced with opset 8.
> onnx fix for opset 7

- src/lc0ctl/leela2onnx.cc
- src/neural/onnx/builder.cc
- src/neural/onnx/builder.h
- src/neural/onnx/converter.cc
- src/neural/onnx/converter.h
- src/neural/onnx/network_onnx.cc
Adds `kernel_shape` as a property to all generated Conv-nodes for generated ONNX-networks, to partially address #1736 . This was specifically done for the onnx2pytorch-package requiring. [The ONNX-standard](https://onnx.ai/onnx/operators/onnx__Conv.html) states that this field is optional, and if not provided it should be inferred just looking at the dimensionality of the weights. These changes make _some_ networks generated by `leela2onnx` readable by `onnx2pytorch`. 
I verified that it works with the network that comes bundled with the latest lc0-release (791556) at least. However, many of the networks fail since `onnx2pytorch` hasn't implemented layer-normalisation, (as was the case with many of the networks I tried (mostly from https://lczero.org/play/networks/bestnets/). I also …
> Make leela2onnx Conv-nodes compatible with onnx2pytorch

- src/engine.cc
- src/mcts/params.cc
- src/mcts/search.cc
- src/mcts/search.h
- src/neural/blas/network_blas.cc
- src/neural/cuda/network_cuda.cc
- src/neural/network.h
- src/neural/network_demux.cc
- src/neural/network_mux.cc
- src/neural/network_rr.cc
- src/neural/onednn/network_onednn.cc
- src/neural/onnx/network_onnx.cc
This is the second part of the auto-configuration changes. It doesn't change the behavior for any explicitly set value, but the new defaults lead to the following:
1. Threads are set according to the backend specified value, plus 1 for non-cpu backends.
2. The backends request 1 thread except for cuda with multi-stream, multiplexing and round-robin.
3. The task workers are set to 0 for cpu backends, otherwise to cpu_cores/(threads-1) up to a max of 4.
4. The multiplexing and roundrobin backends suggest for minibatch the min of the values of the used backends. For the demux backend this is multiplied by the number of (backend) threads.
This is changing the default for cpu backends to 1 thread and may reduce task-workers (apparently this is generally expected of cpu engines). Multiplexing …
> auto setting of threads and task workers

- src/mcts/search.cc
- src/mcts/search.h
This pr suggests to skip the proactively wake up TaskWorkers since it causes performance drop in CPU constraint moment.
**Hardware**:
Intel Icelake 2 sockets/80 physical cores/160 logical cores platform
**OS**:
CentOS 8 Stream with kernel version 6.2
**Benchmark**:
./lc0 benchmark -b eigen --threads=$num_threads -w b30e742bcfd905815e0e7dbd4e1bafb41ade748f85d006b8e28758f1a3107ae3 --num-positions=1
With latest lc0 code, it's observed sometimes the benchmark hit bad case in the moment CPU resource is constraint, and it's due to proactively wake up TaskWorkers.
When CPU resource is constraint, proactively wake up could make SearchWorker off CPU and TaskWorkers on CPU, unfortunately there is nothing in picking_tasks_, so that TaskWorkers will be busy waiting but actually starving. Even if they …
> Skip proactively wake up TaskWorkers for cpu backend

- src/mcts/params.cc
Option TaskWorkers uses default value (-1) outside its range [0, 128]. Fix this by expanding the range to [-1, 128].
---
The out-of-bounds default broke python-chess for me:
```
DEBUG:chess.engine:<UciProtocol (pid=101352)>: Connection made
DEBUG:chess.engine:<UciProtocol (pid=101352)>: << uci
DEBUG:chess.engine:<UciProtocol (pid=101352)>: >> id name Lc0 v0.31.0-dev+git.3f4c157
DEBUG:chess.engine:<UciProtocol (pid=101352)>: >> id author The LCZero Authors.
...
DEBUG:chess.engine:<UciProtocol (pid=101352)>: >> option name TaskWorkers type spin default -1 min 0 max 128
...
DEBUG:chess.engine:<UciProtocol (pid=101352)>: >> uciok
/usr/lib/python3.11/asyncio/unix_events.py:940: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
warnings.warn(
Error: expected …
```
> Fix TaskWorkers range

- README.md
Latest release as of Jan 2024:
https://github.com/LeelaChessZero/lc0/releases/tag/v0.30.0
> Update readme to refer to latest 0.30 release

- scripts/pybind/retval.py
The custom `pybind` implementation for the Python binding has a bug when returning the masks for the input planes.
`Py_BuildValue()` takes a [format string](https://docs.python.org/3/c-api/arg.html) for converting C++ values to Python integers. Lowercase `k` is used for `unsigned long`, and uppercase `K` is used for `unsigned long long`. For `uint64_t`, we want to use the latter.
Previously, the bits were being stripped to 32 bits.
> Fix unsigned int conversion from cpp to Python.

- meson.build
- src/lc0ctl/leela2onnx.cc
- src/neural/xla/hlo_builder.h
- src/neural/xla/onnx2hlo.cc
- src/neural/xla/onnx2hlo.h
- src/neural/xla/print_hlo.cc
In addition to (now optional) `--output=` parameter of `leela2onnx`,
* `--hlo-text-output=filename` to output as text HLO (or stdout if filename is `-`)
* `--hlo-proto-output=filename` to output to binary `HloModuleProto` file
* `--hlo-batch-size` -- for which batch size to generate HLO (333 is the default, to be noticeable in the output file)
* `--hlo-allow-partial-result` -- if conversion fails (i.e. due to ONNX op not being implemented), still output what was converted so far. Useful to look at the progress while implementing new ops.
> Support outputting HLO in leela2onnx

- src/utils/protomessage.cc
Before:
```
{,"key1":"value1""key2":"value2""key3":"value3"}
```
After the fix:
```
{"key1":"value1","key2":"value2","key3":"value3"}
```
> Fix output of a proto as JSON

- src/neural/xla/hlo_builder.cc
- src/neural/xla/hlo_builder.h
- src/neural/xla/onnx2hlo.cc
Added:
* Const versions for Cast, Gather
* Slice `axis` attr support.
* In Gather `axis` is optional
* ReduceProd
* ReduceSumSquare
* Unsqueeze
* Div
* BatchNormalization
> Support TF-generated ONNX files. Plus a few more ops added

- src/neural/xla/network_xla.cc
- src/neural/xla/onnx2hlo.cc
- src/neural/xla/onnx2hlo.h
…d XLA, and only compute the heads that are needed in the XLA backend.
This is extracted from https://github.com/LeelaChessZero/lc0/pull/1986.
> Allow overriding the set of output nodes in ONNX2XLA

- meson.build
- src/neural/xla/network_xla.cc
- src/neural/xla/onnx2hlo.cc
- src/neural/xla/xla_runner.cc
- src/neural/xla/xla_runner.h
- src/neural/xla/xla_tensor.cc
- src/neural/xla/xla_tensor.h
* Move XlaTensor to a separate file
* Remove string-based tensor buffer, only use heap-based `XlaMutableTensor` for all use cases.
* Remove special Lc0InputTensor, use "generic" `XlaMutableTensor` for it
* Both adding a sample to a tensor, and resizing the tensor to be accepted by PjRt Executable is done by the same `XlaMutableTensor::Reshape`
> XlaTensor refactoring, in preparation to variable i/o types.

- meson.build
Use either `-arch=all-major` or for cuda versions < 11.5 that don't have this the equivalent nvcc options ~~(but limit f16 code to architectures that support it)~~. The added complexity to limit fp16 code to newer architectures gave an insignificant build time advantage, so was removed.
Seems to fix the reported cuda NaN issues.
> compile common cuda code for multiple targets

- meson.build
- src/neural/xla/network_xla.cc
Also sets `has_backends` in meson.build. Closes #2012
> increase xla priority

- dist/install-dml.cmd
While testing #2009  I found a bug with the directml install script, probably some recent windows security change makes executables in the same directory unavailable when running it by double clicking, so I removed the lc0.exe check and it will directly install the dlls in the script's directory.
> fix dml install script

- build.cmd
- meson.build
Takes away meson warning for meson 1.1.0 or newer on windows builds.
```WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.```
Added meson kwarg warning fix, the ```run_command``` argument takes a check bool-argument so if check: true, is given and the command fails, meson will error out.
```WARNING: You should add the boolean check kwarg to the run_command call. It currently defaults to false, but it will default to true in future releases of meson.```
> Update meson.build and build.cmd

- src/utils/mutex.h
the current logic includes the x86 simd header any time the platform is !arm, which is backwards
> fix build outside x86_64/aarch64

- .circleci/config.yml
- cross-files/x86_64-darwin
Circleci is phasing out their x86 mac build systems, so we have to migrate to the arm ones.
> circleci: build macos binaries on arm

- src/neural/network.h
v0.31 doesn't show the `WDL_mu` centipawn output because of a typo.
> Fixing has_wdl typo affecting no WDL_mu centipawn output

- src/neural/xla/onnx2hlo.cc
* In compile time, only cast from/to f32/f64/s32/s64.
* Constant evaluation of OpMul.
* Added support of Max op, also with constant evaluation.
* Const ReduceProd also does constant folding for the final reshape.
* OpReshape also handles constant evaluation now.
> A few improvements to the onxx 2 hlo converter.

- src/chess/bitboard.h
The comment on the bitboard function previously stated that "a8 is bit 7, b1 is bit 8". 
All bitboard methods (set, get, reset...) use the following to set the position of the bit on the bitboard: std::uint64_t(1) << pos, with pos being the BoardSquare index that follows the horizontal indexing notation (a1=0, b1=1, c1=2...)
Meaning the bit's position on the bitboard is going to be 0 + pos which means the position of the bit should also follow the horizontal indexing notation.
> adressing issue #825

- src/neural/xla/onnx2hlo.cc
ReudeProd ReduceMean and ReduceSumSquare in opset18 no longer have "axes" as an attribute, but a constant variable.
> fix opset18 handling for reduce ops in xla hlo builing

- src/neural/xla/onnx2hlo.cc
Other ops need similar fixes too, and axes handling is quite repetitive to it makes sense to factor that out, but I'll leave that for future PRs.
> Support negative axes in OpUnsqueeze

- src/mcts/search.cc
The previously used `centipawn` formula #1193 is also used as fallback for `WDL_mu` introduced in #1791 mostly to reproduce the extreme centipawn values in clearly decisive positions users are accustomed to. The formula however was calibrated with the raw (unsharpened) WDL NN output, which means that together with WDL sharpening due to high `WDLCalibrationElo` it climbs too quickly, which also means it takes over faster than intended. `WDL_mu` without the fallback usually produces meaningful evals up to around `+4.5`, which is roughly where the fallback formula should take over. However, in the described scenario with `WDLCalibrationElo: 3600` this already happens below +2, causing a discrepancy in behavior between Lc0 and SF eval roughly like …
> Change centipawn fallback to account for sharper WDL with high WDLCalibrationElo

- src/neural/onnx/converter.cc
- src/neural/xla/network_xla.cc
- src/neural/xla/onnx2hlo.cc
The onnx converter alt_mish option was restricted to fp32, since it was only seen to be useful with onnx-cpu (where it is the default). Recent tests show it may be a bit faster with xla over cuda in fp16 (but not with xla over tpu in bf16), so it is made optionally available everywhere, with the computation done in fp32.
> onnx make alt_mish work with other data types

- src/neural/xla/hlo.proto
- src/neural/xla/xla_runner.cc
The existing code was only working with `device=0`.
> fix xla with multiple devices

- .circleci/config.yml
- appveyor.yml
- cross-files/aarch64-linux-android
- cross-files/armv7a-linux-android
- meson.build
- scripts/appveyor_android_build.cmd
- scripts/appveyor_win_package.cmd
- src/neural/xla/onnx2hlo.cc
This requires some updates to the CI infrastructure:
1. Windows builds move to VS2019 (version 16.11 needed). This required an update of the cudnn build to cuda 10.1.243 and cudnn 7.5.1. At the same time I took the opportunity to update mimalloc to 1.8.7, python to 3.10 and meson to 1.3.0 (preinstalled in the appveyor image).
2. Linux builds are now done on Ubuntu 20.04 with gcc-10 and clang-12 with meson 0.63.
3. Android builds are now done with NDK r27c, using clang-18.
4. Macos required an update to meson 1.3.0 to get a bug fix for ObjC++ standard support.  ~~No changes were needed for the Mac builds as those were already done with clang-14.~~
The change in `onnx2hlo.cc` is to work around a VS2019 compiler bug.
> Move to C++20

- src/utils/mutex.h
- src/utils/spinhelper.h
++ for volatile variables is deprecated in C++20
> Spinlock warning fix

- meson.build
- src/engine_classic.cc
- src/engine_loop.cc
- src/neural/factory.cc
- src/neural/factory.h
- src/neural/shared_params.cc
- src/neural/shared_params.h
- src/neural/wrapper.cc
- src/search/classic/params.cc
- src/search/classic/params.h
- src/selfplay/tournament.cc
- src/tools/backendbench.cc
- src/tools/benchmark.cc
* Have a separate file that defines backend options (that are likely used by all backends)
* Make Backend-to-Weights wrapper use these options.
* Move those options off params.cc (still accessible through that class because it will be changed anyway later)
> Move backend-specific options out of search params.cc

- subprojects/packagefiles/gaviotatb/meson.build
Newer meson versions can't build the rescorer because gaviota tb is written in c, but it will work fine if it is made into a static library.
> fix rescorer build with newer meson

- OpenBench/Makefile
- src/main.cc
* `EXE` parameter now creates binaries in the same directory as makefile (as it should)
* EVALFILE is now recognized
* `./lc0 bench` is now a synonim for `./lc0 benchmark`
> Fix openbench-specific issues

- src/neural/memcache.cc
- src/neural/wrapper.cc
- src/utils/atomic_vector.h
Without mutex.  
Only `AddInput()` is thread-safe; others doesn't make sense to do thread safe.
> Make MemCache / Wrapper backends thread-safe

- .gitignore
- meson.build
- src/chess/callbacks.h
- src/chess/position.h
- src/engine_classic.cc
- src/neural/backend.h
- src/neural/batchsplit.cc
- src/neural/batchsplit.h
- src/neural/memcache.cc
- src/neural/memcache.h
- src/search/instamove/instamove.cc
- src/search/instamove/instamove.h
- src/search/register.h
- src/search/search.h
Instead of it being an option.
> Introduce a "valuehead" search algorithm.

- src/selfplay/game.cc
- src/trainingdata/trainingdata.cc
- src/trainingdata/trainingdata.h
There were two issues:
1. Indexing in the policy array was bad for black moves.
2. To calculate the KL divergence you need to revert any softmax temperature in the policy.
> fix training data generation

- third_party/opencl.hpp
For some reason (maybe because I did install some OS updates), opencl builds started failing again. Turns out I run into the problem fixed by https://github.com/KhronosGroup/OpenCL-CLHPP/pull/321 (merged just a few hours ago). Using the previous release of opencl.hpp avoids it and we don't really need anything new.
> use previous release of opencl.hpp

- src/engine.cc
- src/engine.h
- src/neural/backend.h
- src/neural/batchsplit.cc
- src/neural/memcache.cc
- src/neural/wrapper.cc
Allow backend to update parameters and request reload if needed.  
Make (new) engine controller respect this flag.  
Make backend wrapper restart the backend on its own.
I'm currently adding tests for this few PRs later (not in this because that later PR has API change), you may want to wait for them to be ready (for the case they catch some bug), or not waiting and  finding bugs with your eyes is also fine.
> Support updating backend parameters

- src/neural/backends/network_onnx.cc
The main improvements here are:
1. The `min_batch` option to specify minimum batch size (normally 1, 4 for onnx-trt). Only used with variable batch size.
2. Prefix and directory for engine and timing files.
3. A different engine file per batch size (for fixed batch size).
4. A small cleanup.
> onnx-trt improvements

- src/chess/callbacks.h
- src/engine.cc
- src/engine.h
- src/engine_classic.cc
- src/engine_classic.h
- src/engine_loop.cc
- src/engine_loop.h
- src/main.cc
Register UciResponder through observer pattern, rather than passing to constructor.
> Register UciResponder through observer pattern.

- src/chess/uciloop.cc
- src/chess/uciloop.h
- src/engine.cc
- src/engine.h
- src/engine_classic.cc
- src/engine_classic.h
- src/engine_loop.cc
- src/engine_loop.h
- src/main.cc
* Remove EngineLoop class (merge into UciLoop)
* UciLoop is no longer a class to override handlers
* Make reading from stdin outside of UciLoop
* Tidy up parameter initialization
Also includes changes from #2145 (can be merged either separately or together)
> Remove EngineLoop class

- meson.build
- src/chess/position.cc
- src/chess/position.h
- src/engine.cc
- src/engine_classic.cc
- src/engine_loop.cc
- src/search/classic/node.cc
- src/search/classic/node.h
- src/search/classic/wrapper.cc
Hopefully I didn't mess it up while rebasing to upstream/master
After this change `./lc0 classic` would start old search through new API (except that timer, ponder and syzygy parts are not merged yet)
> Wrapper for old search through new API

- src/engine.cc
`quit` while running search caused the engine to crash.
> Wait for search to finish before destructing Engine.

- src/chess/gamestate.cc
They are already flipped in ParseMove()
> Do not flip moves in getting positions from game_state_

- src/search/classic/search.cc
- src/search/classic/search.h
- src/search/dag_classic/search.cc
- src/search/dag_classic/search.h
This is an old bug in dag's `GetVerboseStats()` that was missing the second to last move when making a cache lookup. It was not getting caught by the `ApplyMove()` assert so a cache lookup was done with the wrong moves and the copy in `GetCachedEvaluation()` was accessing out of bounds. Cache lookups before the new backend interface were more forgiving so this was never noticed.
> dag GetVerboseStats() fix and assorted cleanup.

- src/engine_loop.cc
- src/neural/loader.cc
- src/neural/loader.h
- src/neural/wrapper.cc
Discovered [in chat](https://discord.com/channels/425419482568196106/427066771627966466/1377092504935071904).
Also, remove autodiscovering of `.txt` weight files, we don't support them anymore.
> Allow certain backends to run without network file.

- build.cmd
Update build.cmd to use CUDA_PATH from the system variables automatically set by the installer instead of hard coding it. If it is not defined, clear the paths related to it to avoid setting up invalid paths. If cuda is enabled and CUDA_PATH is not defined, exit as it will not compile. As a bonus, the user can also set the CUDA_PATH variable before executing manually to point to another cuda installation. Any style/logic improvements are very welcome.
> Improve windows build script

- meson.build
- meson_options.txt
Make -march=native a build option so we can turn it off when building binaries to support multiple cpu architectures. Well without having to go into meson.build that is.
> add native_arch as a build option

- src/engine.h
If `go` is the first command then `strict_uci_timing_` is initialized late and the timer is never started. Setting it to `true` ensures the timer is started even in this case.
> set strict_uci_timing_ initially to true

- meson.build
- src/neural/backends/metal/mps/MetalNetworkBuilder.mm
- src/neural/backends/metal/mps/NetworkGraph.h
- src/neural/backends/metal/mps/NetworkGraph.mm
- src/neural/backends/metal/network_metal.cc
A bunch of new warnings have cropped up due to lots of deprecations in MacOs after 13.0. This fixes a bunch of those as well as some pre-existing type warnings. Currently we have the following being addressed:
1.
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/vecLib.framework/Headers/cblas.h:610:6: note: 'cblas_sgemm' has been explicitly marked deprecated here
610 | void cblas_sgemm(const enum CBLAS_ORDER __Order,
```
2.
```
[377/387] Linking target lc0
ld: warning: -undefined error is deprecated
ld: warning: ignoring duplicate libraries: '-lc++'
[379/387] Linking target liblc0_lib.dylib
ld: warning: -undefined error is deprecated
ld: warning: ignoring duplicate libraries: '-lc++'
[381/387] Linking target …
```
> Fix warnings in clang / macos compile process

- src/neural/backends/network_onnx.cc
- src/neural/onnx/builder.cc
It seems tensorrt's engine cache doesn't differentiate between models with the same architecture. Adding the hash of the full onnx model to the engine prefix should take care of it.
> add onnx model hash to trt cache prefix

- meson.build
- meson_options.txt
- src/neural/backends/sycl/cuBlasContext.h
- src/neural/backends/sycl/layers.cc.dp.cpp
I managed to compile Sycl for AMD. I used AMD provided ROCm packages for HIP support. I used Intel provided oneAPI packages for Sycl runtime and DPC++. Both install everything under /opt. Here are default paths to help others repeat the compile without manual paths. Path uses symlinks which point to the latest versioned path.
> Sycl for AMD build improvements

- src/neural/backends/sycl/layers.cc.dp.cpp
ROCm version 7 is under development. It will include hipBLAS 3. The new API uses different enums for datatype and computetype. We can update our code to use the new version while macros map the new compute type to old values for version 2 support.
This change is low priority because AMD only recently released the 6.4.2. I'm the odd one compiling it from the sources.
> Support new hipBLAS 3 API

- src/neural/backends/metal/metal_common.h
This issue only shows up in debug builds on macOS. The Metal backend immediately crashes when an input is added to the computation's batch: https://github.com/LeelaChessZero/lc0/blob/b8cc55ecf6e16d7583ba146ef82882b2fac6fb6f/src/neural/backends/metal/network_metal.h#L48
> Fix Metal backend bug with out of bounds vector access

- src/neural/backends/sycl/common_kernels.dp.cpp
- src/neural/backends/sycl/kernels.h
- src/neural/backends/sycl/layers.cc.dp.cpp
- src/neural/backends/sycl/network_sycl.cc.dp.cpp
I have been working on synchronizations changes for sycl backend. Whole change set will be touching many places. I decided to separate out high impact low risk changes which are already ready. I need to still improve rest of changes a little more.
These changes aim to improve performance by avoiding round trip synchronizations while submitting commands to the GPU. Round trip latency leaves GPU idle for a short moment when CPU is working to enqueue more commands. Worst case performance hit comes for one node evaluation. I decided to compare these changes to the current master using ./lc0 bench --nodes=1 --threads=1 --task-workers=0
I have tested hip on GPU and mkl on CPU
Cuda changes are untest.
Master managed:
Position: 1/10 rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 …
> Avoid sycl waits in forwardEval code paths

- meson.build
Fixes building with `-Drescorer=true -Dlc0=false -Dtest=true`. Also removes about 50 files from a build with `-Dtest=true`
> fix test dependencies

- src/neural/backends/cuda/network_cuda.cc
- src/neural/backends/cuda/network_cudnn.cc
In files network_cudnn.cc and network_cuda.cc the routine showDeviceInfo will not compile because Cuda Toolkit 13 removed the clockRate field from the cudaDeviceProp structure. To retrieve the GPU's clock rate in CUDA Toolkit 13.0 cudaDeviceGetAttribute() API with the cudaDevAttrClockRate attribute must be used.
> updated cuda network files for Cuda ToolKit 13

- .circleci/config.yml
- src/neural/backends/network_onnx.cc
Also replaces the call to `std::format()` that needs a newer c++ library
> build onnx on linux ci

- meson.build
I noticed that system eigen won't be used anymore. I found out that has_header check was missing include path from the dependency.
> Fix system eigen detection

- src/search/classic/search.cc
- src/search/dag_classic/search.cc
libstdc++ include bound checking code when using vector::operator[]. This generates thread sanitizer warnings about reading then the end pointer of vector.
> Silence thread sanitizer warnings in search

- meson.build
- src/chess/board.cc
- src/chess/board.h
- src/chess/board_test.cc
Fix a bug where a piece move starting from opponent's backrank was marked as en passant. This could eliminate one of opponents pieces from the board state.
```
position fen r1bqk1nr/pp1nbpp1/2pp3p/3Pp3/2P1P3/2N1B3/PP2NPPP/R2QKB1R w KQkq - 0 1 moves e2g3 g7g6 f1e2 c6c5 d1d2 e7g5 g3f1 d8e7 f2f3 g5e3 f1e3 d7b6 h2h4 g8f6 g2g4 c8d7 b2b3 h6h5 g4g5 f6h7 a2a4 f7f6 g5f6 e7f6 e1c1 b6c8 d1f1 c8e7 e3g2 e8c8 f3f4 h8f8 c1c2 a7a6 a4a5 d8e8 g2e1 e5f4 e1d3 f6g7 f1f4 h7f6 b3b4 c5b4 d3b4 f6g4 h1f1 f8f4 d2f4 g7d4 e2g4 h5g4 c2b3 c8c7 f1d1 d4c5 e4e5 d6e5 f4e5 c7d8 e5b8 e7c8 d5d6 b7b5 b8c7
go nodes 2
bestmove a1a1
```
> Fix piece moves marked en passant

- src/neural/backends/blas/network_blas.cc
Undefined behavior sanitizer reports invalid enum value when BlasComputation copies activation functions from the network. Activation functions are uninitialized when network doesn't use them. BlasComputation copies them unconditionally. Initializing activation function avoids the error report.
> Initialized activation functions in blas backend
