LeelaChessZero/lc0

- src/neural/network_blas.cc
- src/neural/network_opencl.cc
This commit contains a minor fix on opencl (getoptions<bool>) along with a minor code cleanup (mostly removing auxiliaries variables) on both blas/opencl.
> GetOptions fix on OpenCL.

- README.md
Just a minor spelling fix for README.md.
> Spelling fix for README.md

- src/utils/optionsdict.cc
Wrong second argument to substr, fixed
> Fixed error parsing quotes in optionsdict.cc

- src/mcts/search.cc
- src/mcts/search.h
Should be a fast review and merge
> search.cc cosmetics

- src/chess/uciloop.cc
- src/chess/uciloop.h
- src/engine.cc
- src/mcts/node.h
- src/mcts/search.cc
- src/mcts/search.h
Example: `go infinite searchmoves a2a3 b2b3`
> Add searchmoves functionality

- src/mcts/search.cc
- src/mcts/search.h
- src/selfplay/game.cc
- src/selfplay/game.h
- src/selfplay/tournament.cc
- src/selfplay/tournament.h
Per discussion in #47 (which this replaces), using the design that crem and I both came up with. I've tested that it in fact works: https://ghostbin.com/paste/75mj5
> Implement resign in selfplay games

- src/chess/uciloop.cc
- src/chess/uciloop.h
Without this gameready/resign can end up interleaved with other messages. :(
> Change SendResponse to just call SendResponses to avoid mutex issues.

- src/engine.cc
Tune after 833 games. Better than tune with wrong exe. Probably comparable to original values.
> Update time tuning to tune on proper exe

- appveyor.yml
Example run here: https://ci.appveyor.com/project/borg323/lc0/build/21
Executable direct downloads:
https://ci.appveyor.com/api/buildjobs/dpjxnt4kh2nh4nv3/artifacts/build%2Flc0.exe (opencl)
https://ci.appveyor.com/api/buildjobs/s0v8p7cpq2863i5l/artifacts/build%2Flc0.exe (blas)
> appveyor blas and opencl build for windows

- src/chess/bitboard.cc
- src/chess/bitboard.h
- src/chess/board.cc
Reverts LeelaChessZero/lc0#138
> Revert "Reduced Move from 4 bytes to 2 bytes"

- src/neural/network_cudnn.cu
* Ran clang-format
* Added periods at the end of comments.
* Renamed variables from thisFormat to this_format
(in 2/3 of the file).
No other changes (other than formatting).
> Code formatting of network_cudnn.cu

- .circleci/Dockerfile
- .circleci/config.yml
This is a PR to be applied on top of https://github.com/LeelaChessZero/lc0/pull/166
> [CircleCI] Install protobuf dependency on the docker image

- src/mcts/node.h
- src/mcts/search.cc
As discussed in the pvfix PR, to be merged after that one
> Fix get children visits to do what it says it does

- README.md
> README.md update Ubuntu 16.04 instructions

- README.md
- meson.build
- scripts/bumpversion.py
- src/version.h
- src/version.inc
- version.in
We got a file `version.inc` and a script `bumpversion.py` that can manipulate it. This should define a sane basis for our versioning needs.
> Versioning2

- build-cuda.cmd
Building whole solution works and build all required projects.
> Fix windows-cuda build.

- appveyor.yml
This patch:
1. Installs new deployment authentication token
2. Adds 'windows' to the zip filenames for the release
> Appveyor changes

- src/chess/board.cc
> Remove header file not needed after popcnt removal

- src/mcts/node.cc
Per Discord, to prevent bad data being uploaded to server
Some discussion about the error message wording, by all means submit alternatives
> Add check for invalid training data

- appveyor.yml
The new version of cudnn was released a few days ago. This updates the appveyor script to build against it.
> Appveyor update cudnn to 7.2.1

- src/neural/opencl/OpenCL.cc
This is my best guess for porting https://github.com/gcp/leela-zero/commit/07c908e1346205c6877f8d0520754ebc5c5ebe10 to the opencl backend. Ideally I would like the opinion of @Ttl and @frpays before merging.
> Reduce opencl memory requirements

- src/chess/uciloop.cc
Quick PR as per issue https://github.com/LeelaChessZero/lc0/issues/291
> Shorten name

- README.md
Makes reqs be based on desired goal rather than library names.
> Update generic Linux instructions

- appveyor.yml
- meson.build
The test results will show in the appveyor test tab.
> publish appveyor test results

- meson.build
- meson_options.txt
- src/neural/opencl/cl2.hpp
This pr includes fixes for several build issues:
* The opencl backned no longer builds without blas (due to blas backend refactoring)
* There is no default cudnn include directory
* opencl will not build with newer gcc and with cudnn enabled (cl2.hpp file issues)
* The tensorflow backend looks for the protobuf library, which is now included already included but may gat a different version
> Fix some build issues

- src/engine.cc
- src/mcts/search.cc
- src/mcts/search.h
Needs testing to find elo gain, but several tests have shown that default 0.5 power is not optimal. Probably something like 0.55 or 0.6 is good instead with a lower cpuct of 2 or 1 respectively.
> [WIP] Cpuct and FPU pow exponent scaling

- appveyor.yml
- src/syzygy/syzygy_test.cc
5 man tb files will probably exceed the cache file limit in appveyor.
> Add 3-4 man tb files to appveyor for syzygy testing.

- src/mcts/search.cc
- src/mcts/search.h
Noone used that, usefulness not proven.
> Remove --sticky-checkmate flag.

- src/engine.cc
- src/engine.h
- src/mcts/node.cc
- src/mcts/node.h
Supersedes https://github.com/LeelaChessZero/lc0/pull/257.
> Spend (some portion of) saved time (due to smart pruning) immediately.

- README.md
Update for README.md with compile instructions for Raspberry Pi
> Compile Instructions for Raspberry Pi

- src/engine.cc
- src/mcts/search.cc
UCI Param MultiPv -> MultiPV
FPU reduction 0.9 -> 1.2
Slowmover 2.6 -> 1.0
Immediate time use 0.0 -> 0.6
> Tweaks for v0.18.0-rc1

- FLAGS.md
Add a section in FLAGS.md to briefly explain how to use configuration files.
> Add config file section to FLAGS.md

- src/utils/optionsparser.cc
Was:
./lc0 selfplay player1: --movetime=14
Became:
./lc0 selfplay --player1.movetime=14
> Change format of per-player command line options

- meson.build
- src/engine.cc
- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/mcts/search.h
- src/selfplay/tournament.cc
- src/utils/optionsparser.cc
(as a preparation to search-params separation)
>  Move search parameters to a separate class.

- src/chess/uciloop.cc
- src/chess/uciloop.h
- src/engine.cc
- src/engine.h
- src/selfplay/loop.cc
- src/utils/optionsparser.cc
- src/utils/optionsparser.h
It was almost not used but complicated the code.
> Remove callbacks from parameter handling

- src/engine.cc
- src/mcts/params.cc
- src/mcts/params.h
- src/selfplay/game.cc
- src/selfplay/loop.cc
- src/selfplay/tournament.cc
- src/utils/configfile.cc
- src/utils/optionsparser.cc
- src/utils/optionsparser.h
- src/utils/optionsparser_test.cc
- src/utils/string.cc
- src/utils/string.h
* Also make UCI options case insensitive.
* --futile-move-aversion is now --smart-pruning-factor
* Also write better help to some of options (more is welcome!)
* Also StrSplit had a bug
Fixes #353.
>  Separate UCI from help text.

- src/chess/uciloop.cc
- src/chess/uciloop.h
Prefixes each log line with a Unix-style timestamp.
> Add timestamps to debug logs.

- src/engine.cc
- src/mcts/params.cc
One typo corrected and a few grammar and word order improvements.
> --help typo correction and grammar improvements

- README.md
As per request on discord.
borgToday at 3:14 PM
Can you update the wiki with this and/or create a patch for the readme?
> Add extra documentation for building on linux/ubuntu.

- FLAGS.md
Fixed a lot of text with either bad grammar or bad orthography – or both!
> Correct grammar and/or orthography

- src/mcts/search.cc
- src/mcts/search.h
Also remove mutex from IsSearchActive() and GUARDED_BY annotation from stop_.
> make stop_ atomic and check it in GatherMinibatch()

- src/engine.cc
- src/utils/logging.cc
Also increase move overhead limit to ~27 hours to support playing by
fax.
> Support <stderr> as special name of a logfile.

- src/chess/board_test.cc
This shaves 30 seconds off appveyor builds.
> comment out the 2 slower perft tests

- src/mcts/search.cc
- src/mcts/search.h
> Do not sleep if the entire batch was out-of-order.

- src/engine.cc
- src/engine.h
- src/neural/factory.cc
- src/neural/factory.h
- src/selfplay/tournament.cc
Using 2 helper functions in NetworkFactory, one to add the options and one to do the actual loading.
> Refactor network loading

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
Either in centipawns (default), as as win percentage or Q scaled by 100.
> option to select score displayed

- src/mcts/search.cc
As reported by Swynndla on discord and analyzed by @Videodr0me.
> adjust average depth calculation for multivisits

- src/neural/opencl/OpenCL.cc
> Make convolve1 work with workgroup size of 128

- build-cuda.cmd
> remove cuda_include from build-cuda.cmd

- src/neural/cuda/layers.cc
I can't reproduce the warning, but this looks like it will fix it.
> try to fix cuda warning

- meson.build
This was reported on discord earlier today.
> check availability of opencl include files

- src/engine.cc
- src/engine.h
This fixes #547 as outlined in https://github.com/LeelaChessZero/lc0/issues/547#issuecomment-444700691
> remove UpdateFromUciOptions() from EnsureReady()

- meson.build
This reverts commit 356188a4ec1bfe139732ad8b3288caad4593d696.
> Revert "check availability of opencl include files (#560)"

- meson.build
> update or clone submodule if not there

- src/neural/loader.cc
`./lc0 -w dir/name/` is now detected.
> handle gzread errors

- appveyor.yml
> update openblas used by appveyor

- meson.build
- meson_options.txt
- subprojects/protobuf-3.6.0.wrap
- tensorflow.md
Also adds some notes regrading the build process.
> fix building with tensorflow 1.12

- src/utils/optionsparser.cc
as this conventionally is where it is sent
> Changed output of --help flag to stdout rather than stderr

- src/neural/cuda/network_cudnn.cc
This will help spot some issues quickly.
>  Print cuda and gpu info, warn if mismatches are noticed

- src/neural/cuda/layers.cc
I'm not sure we want this merged, but I got an inquiry about it so here it is.
> Add support for cudnn7 0

- src/neural/cuda/layers.cc
- src/neural/cuda/layers.h
- src/neural/cuda/network_cudnn.cc
Discovered these running valgrind on allie's version of the backend.
> Fix some memory leaks in cuda backend.

- src/neural/blas/network_blas.cc
- src/neural/blas/winograd_convolution3.cc
- src/neural/blas/winograd_convolution3.h
This was reported at least twice on discord recently:
https://discordapp.com/channels/425419482568196106/427066771627966466/574641797595398144
https://discordapp.com/channels/425419482568196106/425419999096733706/582680398534934541
> fix WinogradConvolution3 allocation size

- appveyor.yml
With this the generated zip files will be:
- lc0-vx.y.z-windows-gpu-nvidia-cuda.zip
- lc0-vx.y.z-windows-gpu-opencl.zip
- lc0-vx.y.z-windows-cpu-openblas.zip
> Generate more descriptive zip file names for releases

- meson.build
- meson_options.txt
> also check opencl headers

- src/chess/board.cc
> verify location of kings and rooks when reading fens

- appveyor.yml
This is a temporary fix until meson 0.52.1 is released.
> fix appveyor meson version to 0.51.2 for now

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
I have no idea if this even vaguely does what I suggest in the parameter comment - but it seemed interesting to test out.
> Add a shortsightedness parameter.

- appveyor.yml
Thanks to walidhenine2 on discord for letting me know.
> do not retain pdb files for the tests

- src/mcts/params.cc
> add -v short flag for --verbose-move-stats

- src/neural/opencl/OpenCLParams.h
- src/neural/opencl/OpenCLTuner.cc
- src/neural/opencl/network_opencl.cc
- src/utils/optionsdict.cc
This is for the second part of point 2.1.3 in #976.
> allow changing opencl tuner file

- src/mcts/search.cc
r?@mooskagh Much simpler version of #889 with no tree traversal -- motivated by seeing lc0 drop from +128 avoiding mate-in-3 move 103 because the played move got more visits due to Q=0.999+ to continue the game for 30 moves:
https://www.chess.com/computer-chess-championship#event=ccc11-round-2&game=120
Before:
```
position fen 1Q2Q3/8/k1p5/1q6/8/P2p4/1P2p3/K5R1 w - - 13 103
go nodes 300
e8c8  N:      27 (P:  4.13%) (Q:  1.00000) (T) 
b8a8  N:     107 (P: 16.63%) (Q:  0.99912) 
b8b5  N:     119 (P: 12.21%) (Q:  0.99925) 
b8c8  N:     134 (P: 13.96%) (Q:  0.99926) 
bestmove b8c8 ponder a6b6
```
After:
```
e8c8  N:      42 (P:  4.13%) (Q:  1.00000) (T) 
b8a8  N:      76 (P: 16.63%) (Q:  0.99905) 
b8b5  N:     109 (P: 12.21%) (Q:  0.99928) 
b8c8  N:     109 (P: 13.96%) (Q:  0.99930) 
bestmove …
```
> Prefer checkmate over most visits.

- src/mcts/stoppers/factory.cc
r?@mooskagh or @borg323 or @Tilps
> Enable KldGainStopper only for positive minimum gain.

- src/mcts/stoppers/factory.cc
- src/mcts/stoppers/stoppers.cc
> fix stopper when --smart-pruning-factor=0

- src/chess/callbacks.h
- src/engine.cc
- src/selfplay/game.cc
- src/selfplay/game.h
- src/selfplay/tournament.cc
> Also translate moves to legacy format during selfplay.

- appveyor.yml
Using the dnnl blas functions gives performance similar to mkl on recent processors. However it is considerably slower on old ones (checked on a core 2 against openblas).
> build both openblas and dnnl by default

- src/mcts/stoppers/factory.cc
- src/mcts/stoppers/factory.h
- src/selfplay/game.cc
r?@mooskagh Fix #1018 skipping KldGain and SmartPruning
> Skip adding some stoppers when going infinite.

- appveyor.yml
The release builds will fail without this.
> fix copy-paste error

- src/mcts/search.cc
r?@Tilps Replaces #1022 by supporting differing values to also fix #836. The reason why we need to fix even `v == ±1.0f` checks is that during backup, the current terminal node's value (potentially discounted by short-sightedness) replaces the original (potentially non-terminal) value:
https://github.com/LeelaChessZero/lc0/blob/d34bdfb9afd8ab162c256ab36712958c1779600e/src/mcts/search.cc#L1224-L1227
This is necessary because two children could be backed up to a common parent within the same batch, and we don't want the later backup's value to skew the terminal value of the parent (e.g., slightly away from a draw to look slightly losing/winning thus breaking `GetBestChildrenNoTemperature`'s check for a winning terminal).
> Allow mixed terminal values when converting parents to terminals.

- appveyor.yml
This will contain just lc0, client and COPYING
> also upload a cuda zip without the dlls

- src/selfplay/game.cc
> Don't discard games that are in positions that are already done.

- src/neural/network.h
This is from a discussion we had with @mooskagh a few days ago.
> add comment with the plan for NetworkCapabilities

- src/selfplay/game.cc
Not that such scenarios exist yet.
> Fix black to move logic in main selfplay loop to handle fen with black first scenario.

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
Because there are too many confused people trying to increase it as soon as it reaches 100%.
> Hide cache usage by default.

- appveyor.yml
- src/neural/dx/dx_common.h
- src/neural/dx/layers_dx.h
- src/neural/dx/network_dx.cc
- src/neural/dx/network_dx.h
As ruled by https://discordapp.com/channels/425419482568196106/445928688115122176/676762279634796546
> Rename DirectX 12 backend to dx12

- meson.build
- src/chess/uciloop.cc
This mostly silences ~150 warnings while building zlib.
> reduce msvc warnings

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/selfplay/tournament.cc
Parameters change:
- Use the famous kiudee@ v1 params \o/
- Have a separate set of CPuct params at root (enabled by default in uci mode, disabled by default for selfplay)
- Set MaxConcurrentSearchers to 1 by default
> Adjust parameters.

- meson.build
- scripts/checkdir.py
> move checkdir.py into scripts

- appveyor.yml
Specifically 591226.pb.gz is included
> add a default network to the release zip files

- appveyor.yml
- scripts/appveyor_android_build.cmd
- scripts/appveyor_android_package.cmd
With copious amounts of help from @lealgo, this creates an android apk that is compatible with android guis that support the oex protocol, like droidfish. The lc0 is bundled with net 591226 so that it is ready to run.
> make android apk

- src/mcts/params.cc
- src/mcts/search.cc
> minor changes

- src/neural/encoder.cc
- src/selfplay/game.cc
The one line I left out of the last PR, I guess it was easier than I thought it might be...
> Connect up input format when generating training data to allow v5 FRC.

- build-cuda.cmd
- src/neural/dx/network_dx.cc
- src/neural/dx/network_dx.h
Untested, but it compiles, so that is a start...
> Moves left head support for DX backend.

- README.md
Tested on virgin Buster distro on a Raspi 4, added installation of ninja
> Update to Raspi installation instructions

- src/benchmark/backendbench.cc
- src/benchmark/benchmark.cc
- src/engine.cc
- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/stoppers/factory.cc
- src/neural/factory.cc
- src/selfplay/game.cc
- src/selfplay/loop.cc
- src/selfplay/tournament.cc
- src/utils/configfile.cc
- src/utils/optionsdict.h
- src/utils/optionsparser.cc
- src/utils/optionsparser.h
In case you ever wondered why we need that `GetId()` everywhere, it was a temporary solution I wanted to finish before going to bed, so that "next week" I'd fix it.
Finally, that "next day" happened! \o/
> Get rid of GetId()

- src/mcts/search.cc
- src/mcts/search.h
> Fix assert in GetBestChildrenNoTemperature

- src/chess/callbacks.h
- src/chess/pgn.h
- src/selfplay/game.cc
- src/selfplay/game.h
- src/selfplay/loop.cc
- src/selfplay/tournament.cc
- src/selfplay/tournament.h
Also has a bugfix, 0 move pgn games were being incorrectly ignored when loading the book.
> Support for selfplay from books with fen tag.

- src/utils/optionsparser.cc
- src/utils/optionsparser.h
Fixes issue #548 
The Android build needs PR #1166 to be merged.
> Validate string values for integer flags

- README.md
Tested on Ubuntu 16.04 virtual machine.
> Update Readme section for Ubuntu 16.04

- changelog.txt
Hopefully I haven't missed too much...
> Update changelog in preparation for 0.25.0-rc1

- src/mcts/node.cc
- src/neural/writer.h
- src/selfplay/game.cc
I almost did this rename back when I wrote the original PR - just suffering from too much laziness :P
> Rename training data variables for clarity, and fix bug with training data exposed.

- src/chess/board.cc
- src/chess/board.h
- src/chess/position.cc
- src/chess/position.h
- src/mcts/node.cc
- src/mcts/search.cc
- src/neural/encoder.cc
- src/syzygy/syzygy.cc
The name `no_capture_ply` is misleading in places since a pawn push can reset the counter as well.
> Rename no_capture variable and functions to rule50

- README.md
Tested on a rpi zero with raspbian "buster". I looked into adding gcc-8 to an old raspbian but I gave up. It's way easier to upgrade to buster that has the right compilers.
> Update the rpi section of README

- src/mcts/search.cc
An attempt at fixing this issue:
https://github.com/LeelaChessZero/lc0/issues/1200
> MLH verbose stats - Issue 1200 

- FLAGS.md
Replaced old flag name with new flag name.
> Updated FLAGS.md with logfile flag

- CONTRIBUTING.md
Changed it from 'sqahsed' to 'squashed'.
> Fixed a typo in CONTRIBUTING.md

- README.md
Update git clone to the current latest version and add git checkout
> Update Readme about using git

- src/mcts/search.cc
- src/mcts/stoppers/stoppers.cc
- src/mcts/stoppers/timemgr.h
Not going to gain any elo, but it seems consistent with the meaning of smart pruning being enabled.
> Allow smart pruning to terminate search if win is known.

- src/mcts/search.cc
> Switch verbose precision when value would round up to 100.

- src/neural/cuda/fp16_kernels.cu
For those without custom_winograd but using large net... (I think thats the only case this applies :P)
> Add SE optimization for 384 filters.

- src/benchmark/benchmark.cc
- src/mcts/stoppers/common.cc
- src/mcts/stoppers/stoppers.cc
- src/mcts/stoppers/stoppers.h
- src/selfplay/game.cc
Also disable this smart pruning in benchmark and selfplay that don't support self pruning setting.
> Don't do any smart pruning if smart pruning factor is 0 or lower.

- src/mcts/stoppers/alphazero.cc
refactored the input value to pct.
Also updated documentation at
https://github.com/LeelaChessZero/lczero.org/pull/44/
> alphazero input value to pct 

- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
It never quite proved itself and it is almost certainly obsolete now that MLH is a real thing.
> Remove shortsightedness

- src/mcts/node.cc
- src/neural/encoder.cc
- src/neural/encoder.h
- src/selfplay/game.cc
Just to get the code written to show I'm ready for it to be in 0.26...
I'll do a cleanup to introduce some helper functions - just need to decide where to put them...
> Add support for canonical_hectoplies and canonical_hectoplies_armageddon

- src/syzygy/syzygy.cc
"Found 145WDL" --> "Found 145 WDL"
> Add a space in the stderr message for WDL files

- src/neural/blas/network_blas.cc
I haven't found a configuration where a value more than 1 is generally useful, while the confusion created has been considerable.
> remove blas_cores backend option

- src/utils/optionsparser.cc
- src/utils/optionsparser.h
This is not being used, and as the guilty party I'm removing it. I didn't do a straight revert of https://github.com/LeelaChessZero/lc0/commit/9d374646c527e5575179d131c992eb9b2ddc27dc as it also included a small comment fix.
> remove --help-md option

- src/neural/network_record.cc
This takes advantage of the specific pattern of requests made to any given computation to avoid having to store the entire list of requests.
It is a bit 'more' fragile, but given how fragile it already is, I think the disk space and load time savings are worth it.
10 million nodes search takes about 1GB file now meaning 40 million node searches are a plausible replay possibility.
Also make it more explicit that only the first instance of a hash value in the replay file is used.  This was needed to make the behavior correct, but its good to be clear anyway. (It also slightly reduces the memory usage at runtime during replay, even above the 3 fold reduction from reduced recording data.)
> Reduce record backend stored file size by a factor of 3.

- meson.build
We should have done this a long time ago.
> enable lto by default

- src/mcts/search.cc
- src/mcts/stoppers/factory.cc
- src/mcts/stoppers/smooth.cc
- src/mcts/stoppers/timemgr.h
- src/neural/network.h
(also possible to add other conditions to extend the search).
So far in my sample of 2 games it didn't perform very well.
new params to tune:
`--time-manager=smooth-experimental(init-piggybank=0.1,per-move-piggybank=0.05,max-piggybank-use=0.7,max-piggybank-moves=10.0)`
> Extend thinking time if max Q is not max N.

- src/selfplay/loop.cc
- src/selfplay/tournament.cc
> selfplay logging

- src/mcts/stoppers/common.cc
- src/mcts/stoppers/stoppers.h
- src/selfplay/game.cc
Fix the issue Number of visits goes above 4000000000 #1313
> Fix the issue Number of visits goes above 4000000000

- src/neural/loader.cc
- src/neural/opencl/network_opencl.cc
- src/neural/writer.cc
- src/utils/configfile.cc
- src/utils/filesystem.h
- src/utils/filesystem.posix.cc
- src/utils/filesystem.win32.cc
> change default directories

- .circleci/Dockerfile
- .circleci/config.yml
This fixes CircleCI broken builds (reported by @Naphthalin )
> Install Eigen library into the Docker image used by CircleCi

- src/neural/encoder.cc
Its very straight forward - training won't need any additional logic, just needs code to treat v2 like hectoplies.
> Implement canonical v2 logic.

- meson.build
This generates larger executables, but the default was reported to have performance issues (at least with certain cards/drivers).
> alternative way to support multiple cuda architecture

- meson.build
- src/main.cc
- src/mcts/search.cc
- src/mcts/search.h
- src/neural/network_demux.cc
- src/neural/network_mux.cc
- src/utils/numa.cc
- src/utils/numa.h
This is a first effort for #1382. Needs testing and cleanup.
> try to allocate threads across windows processor groups

- appveyor.yml
- scripts/appveyor_win_build.cmd
- scripts/appveyor_win_package.cmd
The current cuda package is renamed to cudnn
> create separate cuda backend package

- src/mcts/params.cc
Surely its time?
People can argue about exact thresholds and stuff, but I don't think any serious net wants it off anymore.
> Make MLH default on.

- src/benchmark/benchmark.cc
Can't parse output with gnuplot otherwise...
> Consistent formatting in benchmark output.

- README.md
Sort out gtest for Mac
Fixes #1433
> Update Mac install instructions

- src/chess/position.h
- src/main.cc
- src/mcts/node.cc
- src/mcts/node.h
- src/mcts/params.cc
- src/mcts/params.h
- src/mcts/search.cc
- src/mcts/search.h
- src/neural/cache.cc
- src/neural/cache.h
- src/selfplay/game.cc
- src/utils/cache.h
- src/utils/fastmath.h
- src/utils/mutex.h
Specifically the node size isn't reduced.  Lots of extra code duplication.
I also dropped HashKeyCache from this branch since it wasn't practical to make it optional.
I can't really test how much benefit HashKeyCache is - since the cache isn't that much of a hotspot on my machine, although its definitely one on others...
The default values for MaxCollisionEvents/Visits are also unchanged in this PR - but the potential issues of leaving them as per their defaults still apply.
> An alternative multigather which skips a few details in order to be able to make it optional.

- src/mcts/search.cc
- src/mcts/search.h
> Remove FetchSingleNodeResult duplication.

- src/mcts/search.cc
- src/mcts/search.h
> Rewrite legacy ExtendNode in terms of new ExtendNode.

- src/chess/position.h
- src/mcts/search.cc
- src/mcts/search.h
3% increase in nps on benchmark.
100% increase in nps in #1 positions.
> Increase use of task workspace.

- src/mcts/node.cc
> check for illegal move

- src/mcts/search.cc
- src/mcts/search.h
- src/mcts/stoppers/stoppers.cc
> Fix compile error due to missing #include <condition_variable>.

- appveyor.yml
- 744005 for blas and android
- 751390 for everything else
> target specific default net

- appveyor.yml
- src/mcts/params.cc
Those seem like better defaults now that multi-gather is enabled.
> update blas defaults

- src/syzygy/syzygy.cc
Fix issues #706 (Uses of exit instead of Exception)
> Uses of exit instead of Exception

- src/mcts/search.cc
> disable max_needed optimization when filtering root moves

- src/neural/cuda/network_cuda.cc
- src/neural/cuda/network_cudnn.cc
- src/neural/dx/network_dx.cc
- src/neural/onednn/network_onednn.cc
> more stable softmax

- appveyor.yml
> update default nets

- src/neural/blas/fully_connected_layer.cc
- src/neural/blas/fully_connected_layer.h
- src/neural/blas/network_blas.cc
- src/neural/blas/se_unit.cc
- src/neural/blas/se_unit.h
- src/neural/shared/activation.cc
- src/neural/shared/activation.h
The absolute minimum required to support evaluating T79 using blas.
Only tested with Eigen, but I did try both start pos and a position with some promotion options (including promotion by capture)
> Attention blas (No policy encoder block support)

- src/python/weights.h
> Update number of history planes in weights.h

- src/chess/bitboard.h
> make use of IsValidCoord method

- src/lc0ctl/onnx2leela.cc
> Don't check for onnx domain, tf2onnx doesn't populate this field.

- scripts/checkdir.py
I have been meaning to send this for some time but I forgot about it.
> python build helper compatibility fix

- src/neural/cuda/network_cuda.cc
- factor of sizeof(DataType) was missing.
> Fix attention head size

- src/neural/metal/network_metal.cc
- Fixed conv policy map bug.
- Increased priority of metal backend above opencl
> Increase priority and fix conv policy bug in metal backend.

- src/neural/blas/network_blas.cc
- src/neural/metal/mps/MetalNetworkBuilder.mm
- src/neural/metal/mps/NetworkGraph.h
- src/neural/metal/mps/NetworkGraph.mm
- src/neural/onnx/adapters.cc
- src/neural/onnx/converter.cc
Fixing a bug in the calculation of scaling factor for multi-head attention in encoder layers.
> Fix error in mha scaling in encoder layers.

- appveyor.yml
This one will also fix the onednn package build issue as the zip used includes some files that were missing in the previous one.
> update onednn version

- src/neural/cuda/common_kernels.cu
- src/neural/cuda/winograd_helper.inc
Fix nan overflow on cuda softmax
> Fix softmax cuda

- src/neural/onnx/converter.cc
This was missed during a merge.
> fix onnx final mlh activation

- meson.build
- src/neural/blas/encoder.h
- src/neural/blas/layer_norm.ispc
- src/neural/blas/network_blas.cc
- src/neural/shared/activation.cc
- src/neural/shared/activation.ispc
Speeds up T78 policy head with blas, which is not very noticeable on the full net evaluation, but should come in handy in the future.
> BLAS performance improvement for attention policy parts.

- src/neural/metal/network_metal.cc
Update metal backend proto enum references to match new proto updates in PR #1865
> Update metal proto enum references

- src/neural/onnx/network_onnx.cc
The upcoming release of onnxruntime 1.16 breaks our build because they forbid direct assignment from already encoded `uint16_t` to their `Float16_t`. They do provide access to the `uint16_t val` member, but this was named `value` in previous versions, so it can't be used for direct assignment in a portable way.
> fix Float16_t related onnx build issues

- src/rescorer/rescoreloop.cc
I didn't want to add this to #1957
> fix rescorer warnings

- src/neural/xla/network_xla.cc
Also have more sensible defaults for batch size and steps.
> XLA backend only filled every 4th sample, fix it.

- src/neural/xla/hlo.proto
- src/neural/xla/hlo_builder.cc
- src/neural/xla/hlo_builder.h
- src/neural/xla/network_xla.cc
- src/neural/xla/onnx2hlo.cc
- src/neural/xla/print_hlo.cc
* Dependent computation support
* Helper class for HloShapes instead of suing protos directly
* Ops:
> Update ONNX-to-HLO converter to support T75 nets

- src/neural/xla/onnx2hlo.cc
Supposedly fixes build for some Visual Studio targets.
> Add missing headers

- src/neural/onnx/converter.cc
This was found while reviewing #1978, and took the opportunity to do some refactoring I wanted to do at some point.
> fix onnx ffn alpha multiplication

- appveyor.yml
Reported to fix the android blas issues with rc1.
> update android openblas to 0.3.27

- appveyor.yml
Remove temporary cache clearing code I mistakenly left in.
> fix openblas appveyor build

- src/neural/xla/hlo_builder.cc
- src/neural/xla/xla_runner.cc
- src/neural/xla/xla_tensor.cc
- src/utils/fp8_utils.h
Missing #include <algorithm> caused a cryptic error message.
> Fix build for GCC 14.1

- src/utils/configfile.cc
> chore: update configfile.cc

- src/chess/position.h
- src/neural/encoder.cc
- src/neural/encoder.h
Needed as a step for old to new backend interface wrapper.
> Make EncodePositionForNN accept span<Position>

- scripts/compile_proto.py
* `reserved` keyword is now supported.
* It's possible to reserve fields by number, or by name (quotes are optional).
* string fields now have `mutable_X()` function.
> Minor changes to proto generation

- meson.build
- src/chess/gamestate.cc
- src/chess/gamestate.h
- src/chess/position.h
- src/search/artifacts.h
- src/search/instamove/instamove.cc
- src/search/instamove/instamove.h
- src/search/register.cc
- src/search/register.h
- src/search/search.h
The code is not plugged to anywhere, but it compiles and links.
> Introduce new search API, add a sample "policy head" algorithm

- src/neural/backend.h
- src/neural/factory.cc
- src/neural/loader.cc
- src/neural/loader.h
- src/neural/register.cc
- src/neural/register.h
- src/neural/shared_params.cc
- src/neural/shared_params.h
- src/neural/wrapper.cc
- src/neural/wrapper.h
Plus some small refactorings around.
> Adding BackendManager functions to create a backend.

- meson.build
- src/engine_classic.cc
- src/neural/memcache.cc
- src/neural/memcache.h
- src/neural/shared_params.cc
- src/neural/shared_params.h
- src/search/classic/stoppers/common.cc
- src/search/classic/stoppers/common.h
- src/selfplay/tournament.cc
- src/tools/benchmark.cc
- src/utils/cache.h
Also move kNNCacheSizeId to Shared Backend params.
> Implement node cache as a backend layer.

- meson.build
- src/chess/gamestate.cc
- src/chess/gamestate.h
- src/chess/position.cc
- src/chess/position.h
- src/engine.cc
- src/engine.h
- src/engine_classic.cc
- src/engine_classic.h
- src/engine_loop.cc
- src/engine_loop.h
- src/main.cc
- src/neural/backend.cc
- src/neural/register.cc
- src/neural/register.h
- src/neural/wrapper.cc
- src/search/instamove/instamove.cc
- src/search/instamove/instamove.h
- src/search/register.cc
- src/search/register.h
- src/search/search.h
- src/utils/commandline.cc
- src/utils/commandline.h
This PR plugs everything together.
And the new `policyhead` search algorithm works, through the new Backend interface!
> Plug new Search and Backend APIs to the engine

- src/tools/benchmark.cc
Let's push it how to get OpenBench running, and revisit proper solution afterwards.
> Update benchmark defaults for OpenBench

- AUTHORS
Generated using `git log --pretty=format:"%an" | sort -u`, and then added `Google LLC` manually as they hold the copyright of some code by some of us.
There are a few obvious duplicates with different spelling, but I believe it's more correct like this (plus less work to generate and update).
> Add AUTHORs file

- src/neural/backends/opencl/OpenCL.h
- third_party/opencl.hpp
Fixes opencl build issues with clang.
> replace cl2.hpp with latest opencl.hpp

- src/chess/uciloop.cc
- src/chess/uciloop.h
- src/engine_loop.cc
- src/engine_loop.h
- src/main.cc
- src/selfplay/loop.cc
- src/selfplay/loop.h
- src/selfplay/tournament.cc
- src/selfplay/tournament.h
1. Separate responder off UciLoop
2. Make selfplay not depend on UciLoop
3. (as the result of 2) Delete "interactive" selfplay mode -- it was not used anyway.
> Separate responder off UciLoop

- src/chess/callbacks.h
- src/chess/uciloop.cc
- src/engine_classic.cc
* Move ShowWDL and ShowMLH parameters to the UciResponder.
* Also show WDL by default now.
> Move ShowWDL and ShowMLH parameters to the UciResponder

- src/engine.cc
- src/engine.h
Includes changes from https://github.com/LeelaChessZero/lc0/pull/2149
> Support for ponder in Engine

- src/search/dag_classic/wrapper.cc
> correct tt clearing order

- src/search/classic/search.cc
> fix GetVerboseStats() cleanup bug

- src/chess/bitboard.h
- src/chess/board.cc
- src/chess/board.h
- src/chess/position.cc
- src/chess/position.h
- src/chess/position_test.cc
- src/trainingdata/rescorer.cc
It's more convenient to have it as one string, and clickable link is quite useful too.
> Use FEN (as URL) for chess board DebugString()

- src/chess/uciloop.cc
- src/engine.cc
- src/engine_loop.cc
- src/main.cc
- src/search/classic/stoppers/common.cc
- src/search/classic/stoppers/factory.cc
- src/search/dag_classic/stoppers/common.cc
- src/search/dag_classic/stoppers/factory.cc
Add back all simple mode options from the previous release. Also disable all other modes and leave only search in simple mode.
> complete simple mode

- src/chess/uciloop.cc
> custom setoption parsing

- src/neural/backends/sycl/common_kernels.dp.cpp
- src/neural/backends/sycl/fp16_kernels.dp.cpp
- src/neural/backends/sycl/winograd_helper.h
- src/neural/factory.h
- src/neural/register.h
- src/search/register.h
I had to add some superfluous `[[maybe_unused]]` attributes as icx gets confused.
> fix some icx warnings

- README.md
All other install instructions are like that.
> Start Count at One for Windows Install Instructions

- meson.build
- src/neural/backends/blas/convolution1.cc
- src/neural/backends/blas/fully_connected_layer.cc
- src/neural/backends/blas/winograd_convolution3.cc
- subprojects/eigen.wrap
Also simplify eigen includes and update eigen.wrap to have a `source_fallback_url` as the default Eigen server seems to have connectivity problems once in a while.
> fix for eigen dependency issue

- src/search/classic/search.h
- src/search/dag_classic/node.cc
- src/search/dag_classic/node.h
- src/search/dag_classic/search.cc
These are cherry picked changes from dag-update. I have to resolve some conflicts.
> Concurrent task workers

- build.sh
- meson.build
Meson version 0.57 is the first one to accept c++20.
> fix meson warnings

- src/search/dag_classic/search.cc
A new position can free the root_node_ of the old Search object. Search object is only freed after the new Search has been created. This means root_node_ cannot be accessed after Search::Wait has been called.
Steps to reproduce the bug:
```
go nodes 50
position startpos moves e2e4 e7e5
go nodes 50
position startpos moves d2d4 d7d5
go nodes 50
```
> Fix use-after-free when old Search is destroyed
